Removed alpha from ForceShiftedLJ and LJ
glotzerlab/hoomd-blue pull request #1010
Opened 2021-05-25 17:03 UTC by pepak13

## Description
Removed the alpha parameter from the ForceShiftedLJ and LJ 

Added the struct param_type for ForceShiftedLJ as it wasn't there before. 

closes #800 

## Motivation and context

Alpha no longer a feature in Hoomd3.0

## How has this been tested?

Ran test sims of simple spheres using changed pair potentials

## Change log

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2021-05-26 13:44 UTC, joaander requested changes
Thanks!

Sorry for the ill-defined issue, it must have been out of date with respect to other changes in the code. I found and removed a couple more uses of alpha in comments to avoid confusion. I have one change request.

2021-05-26 13:44 UTC, joaander commented on hoomd/md/EvaluatorPairForceShiftedLJ.h
> +#endif
```suggestion
typedef EvaluatorPairLJ::param_type param_type;
```
We can revert this change. This line of code borrows the identical param_type struct from `EvaluatorPairLJ` without duplicating code.

2021-06-02 16:39 UTC, joaander commented
@mariaward10 do you have any questions about reviewing this pull request?

2021-06-02 20:35 UTC, mariaward10 approved these changes
I went over the changes and they look good, seem ready to go.

2021-06-03 19:33 UTC, joaander approved these changes
Thanks!

2021-06-03 19:34 UTC, merged