Tests for angle, bond and dihedral potentials
glotzerlab/hoomd-blue pull request #1016
Opened 2021-05-25 20:25 UTC by Charlottez112

@danevans09 and I added some tests for the angle, bond and dihedral potentials. The tests for dihedral potentials are not passing and we are not sure why.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2021-05-26 16:48 UTC, b-butler commented
The tests still do not work for dihedral, but I fixed a mostly documentation bug about `n` for the `Harmonic` potential that I noticed when trying to review to offer comments on what to do. I also simplified the dihedral snapshot factory. I am not sure now why the energies are off. I also do not know what was done to generate the reference forces.

2021-05-26 22:15 UTC, Charlottez112 commented
> The tests still do not work for dihedral, but I fixed a mostly documentation bug about `n` for the `Harmonic` potential that I noticed when trying to review to offer comments on what to do. I also simplified the dihedral snapshot factory. I am not sure now why the energies are off. 

I think it has to do with how the four particles are connected (the order of the particle coordinates), which may affect the value of the dihedral angle. (Four particles cannot define two planes.) I updated the positions of the four particles in the `test_dihedral_harmonic.py`  to make the test pass, but it seems like it only works for pi/4 now.

> I also do not know what was done to generate the reference forces.

We used Matlab/ Mathematica to manully compute the potential energies/ forces for the initial configuration.

2021-05-28 21:14 UTC, danevans09 commented
The `OPLS` forces and energies all pass now, however the `Harmonic` forces and energies do not. The `Harmonic` tests pass when n*phi is equal to pi

2021-05-29 03:03 UTC, Charlottez112 commented
> The `OPLS` forces and energies all pass now, however the `Harmonic` forces and energies do not. The `Harmonic` tests pass when n*phi is equal to pi

I only updated the values in `test_dihedral_harmonic.py` so the old values in `test_dihedral.py` were wrong. To avoid confusion, I deleted `test_dihedral_harmonic.py` and updated the correct values. I also updated the OPLS forces. They should be negative. 

The entire test for the dihedral potential passed on my local device and the "real" dihedral angle used in the calculation is `-pi/4`.

I think it would be very helpful if we could add some documentation on how this angle is determined. Now the explanation is a little vague. I had to guess the real dihedral angle by trying different orders of the four particles. What are your thoughts @b-butler @joaander

2021-06-02 16:21 UTC, joaander commented
> I think it would be very helpful if we could add some documentation on how this angle is determined. Now the explanation is a little vague. I had to guess the real dihedral angle by trying different orders of the four particles. What are your thoughts @b-butler @joaander

Please create an issue that requests this documentation.

2021-06-02 16:35 UTC, joaander approved these changes
Thanks! 

I have one suggestion to document a change, but other than that this is great.

@b-butler do you have any comments?

2021-06-02 16:35 UTC, joaander commented on hoomd/md/OPLSDihedralForceCompute.cc
>      pybind11::dict params;
```suggestion
    pybind11::dict params;
    // note: the values stored in params are precomputed k/2 values
```
This * 2 is correct, but the class documentation doesn't make it very clear how this is stored. Add this as a reminder.

2021-06-09 16:16 UTC, b-butler requested changes
Thanks for the work. :smiley: I have left a few comments, these generally apply to all three or two of the three test files, so please make the changes in all files to resolve a comment.

2021-06-09 16:16 UTC, b-butler commented on hoomd/md/pytest/test_angle.py
> +                                           ]]
```suggestion
            base_positions = np.array([
                [-d * np.sin(theta_rad / 2), d * np.cos(theta_rad / 2), 0.0],
                [0.0, 0.0, 0.0],
                [d * np.sin(theta_rad / 2), d * np.cos(theta_rad / 2), 0.0]
            ]
            # move particles slightly in direction of MPI decomposition which
            # varies by simulation dimension
            nudge_dimension = 2 if dimensions == 3 else 1
            base_positions[:, nudge_dimension] += 0.1
            s.particles.position[:] = base_positions
            s.particles.types = particle_types
```

Make this kind of change in other snapshot factory methods created in this PR as well please

2021-06-09 16:16 UTC, b-butler commented on hoomd/md/pytest/test_angle.py
> +def test_before_attaching(angle_and_args):
```suggestion
@pytest.mark.parametrize("angle_cls, potential_kwargs", get_angle_and_args())
def test_before_attaching(angle_cls, potential_kwargs):
```
Make this change in the function and all other functions that use this and similar fixtures in the tests.

2021-06-09 16:16 UTC, b-butler commented on hoomd/md/pytest/test_angle.py
> +        snap.angles.group[0] = (0, 1, 2)
Is `triplet_snapshot_factory` used anywhere else other than `test_angle.py`? If not this this should be in that factory function.

2021-06-09 16:16 UTC, b-butler commented on hoomd/md/pytest/test_angle.py
> +    for key in args.keys():
```suggestion
    for key in args:
```

2021-06-09 16:16 UTC, b-butler commented on hoomd/md/pytest/test_angle.py
> +    for key in args.keys():
```suggestion
    for key in args:

2021-06-09 16:16 UTC, b-butler commented on hoomd/md/pytest/test_angle.py
> +                         get_angle_args_forces_and_energies())
split up the tuple here as suggested above.

2021-06-10 03:23 UTC, vyasr commented
Sorry I lost track of being requested here. I won't be able to look at this until early next week, but please ping me if I haven't reviewed by next Tuesday or so (if all other reviewers are happy with the state of this code before then I'm also fine if my review request is removed).

2021-06-11 17:26 UTC, b-butler approved these changes
LGTM

2021-06-11 17:29 UTC, merged