Fix compiling error in ForceComposite.cc
glotzerlab/hoomd-blue pull request #1037
Opened 2021-06-14 20:23 UTC by danevans09

## Description

I changed two assert statements to use the correct variable for the particle index and also defined an `ntypes` variable that was used in one of the assert statements.
## Motivation and context
The `ForceComposite.cc` file does not compile because of two undefined variables being used.

## How has this been tested?

The code now compiles and the tests in `test_rigid.py` all pass.

## Change log

```

```

## Checklist:

- [X] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [X] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [X] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2021-06-15 12:12 UTC, joaander requested changes

2021-06-15 12:12 UTC, joaander commented on hoomd/md/ForceComposite.cc
> +    unsigned int ntypes = m_pdata->getNTypes();
```suggestion
```
This generates a compiler warning as `ntypes` is not used in Release builds.

2021-06-15 12:12 UTC, joaander commented on hoomd/md/ForceComposite.cc
> +            assert(snap.type[particle_tag] < ntypes);
```suggestion
            assert(snap.type[particle_tag] < m_pdata->getNTypes());
```
Call it directly here to avoid the warning.

2021-06-16 15:42 UTC, b-butler approved these changes
Thanks @danevans09! LGTM

2021-06-16 15:47 UTC, joaander approved these changes

2021-06-16 15:47 UTC, merged