Implement custom mutability error for initialized simulations
glotzerlab/hoomd-blue pull request #1098
Opened 2021-08-11 18:50 UTC by AlainKadar

## Description

Define a custom error which explains that read only attributes cannot be modified after a simulation has been run. Modify attribute setting methods so that this error is called when appropriate

## Motivation and context

Resolves #1043 

## How has this been tested?

Attempting to change the filename of a gsd writer successfully raises the error

## Change log

```

```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2021-08-11 19:18 UTC, b-butler requested changes
Thanks for the PR. I have one suggestion, and don't forget to update the tests for classes that should raise this new error.

2021-08-11 19:18 UTC, b-butler commented on hoomd/operation.py
> +                raise MutabilityError
```suggestion
                raise MutabilityError(attr)
```

2021-09-01 19:03 UTC, joaander commented on hoomd/pytest/test_box_resize.py
> +    box_op = hoomd.update.BoxResize(box1, box2, var, trig)
```suggestion
    box_op = hoomd.update.BoxResize(box1=box1, box2=box2, variant=var, trigger=trig)
```
The `master` branch changed the order of these arguments, causing the test to fail. Use keyword arguments so they are passed without ambiguity.

2021-09-02 12:32 UTC, joaander commented
To help move this forward, I committed the suggested changes and fixed a test that was failing because of changes on merged in #1115.

2021-09-02 12:34 UTC, joaander commented
Suggested change log entry:
```
Added:

- ``MutabilityError`` exception when setting read-only operation parameters.
```

Please suggest change log entries in future pull request descriptions.

2021-09-02 13:23 UTC, AlainKadar commented
Thanks for commits and fixes, @joaander

2021-09-02 22:47 UTC, joaander commented
This pull request is passing and ready for final review.

2021-09-03 17:25 UTC, b-butler approved these changes
LGTM

2021-09-03 17:25 UTC, merged