Move Active force rotational diffusion to updater
glotzerlab/hoomd-blue pull request #1099
Opened 2021-08-13 14:51 UTC by b-butler

## Description

This PR moves the rotational diffusion part of `hoomd.md.force.Active` and subclasses to its own updater. In addition this PR addresses various bugs or limitations in other parts of the code that lead to errors or difficulties in adding the updater. For more info on those, see the git commit messages.

## Motivation and context

This addresses #898 and bugs in the existing code base.

Resolves #898

## How has this been tested?

An additional test file has been created for testing the updater.

## Change log

```
Added: A new roational diffusion updater for use with Active Forces ``hoomd.md.update.ActiveRotationalDiffusion``.
```
or
```
Changed: Active force rotaional diffusion is now managed by ``hoomd.md.update.ActiveRotationalDiffusion``.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2021-08-13 14:53 UTC, b-butler commented
This PR needs to be merged after #1053 which shouldn't be a problem since tests won't pass until then.

2021-08-23 14:06 UTC, joaander reviewed
The overall structure is fine. I will make a detailed review once tests are passing.

2021-08-31 11:18 UTC, joaander requested changes
Thanks! Here is another round of improvements to the documentation. Also, merge master up into this branch and resolve conflicts.

2021-08-31 11:18 UTC, joaander commented on hoomd/md/force.py
> +        constant during the simulation.
```suggestion
        Active force vector in the local reference frame of the particle
        :math:`[\mathrm{force}]`.  It is defined per particle type and stays
        constant during the simulation.
```
Clearer language.

2021-08-31 11:18 UTC, joaander commented on hoomd/md/force.py
> +        particle type and stays constant during the simulation.
```suggestion
        Active torque vector in the local reference frame of the particle
        :math:`[\mathrm{force} \cdot \mathrm{length}]`. It is defined per
        particle type and stays constant during the simulation.
```

2021-08-31 11:18 UTC, joaander commented on hoomd/md/force.py
> +                with the updater. This is not settable after construction.
```suggestion
```
This is not an argument of the method.

2021-08-31 11:18 UTC, joaander commented on hoomd/md/force.py
>      should be added to all particles similar to :py:class:`Active`. The
"all particles" should instead be "particles selected by the filter."

2021-08-31 11:18 UTC, joaander commented on hoomd/md/force.py
> +        constant during the simulation.
```suggestion
        Active force vector in the local reference frame of the particle
        :math:`[\mathrm{force}]`.  It is defined per particle type and stays
        constant during the simulation.
```

2021-08-31 11:18 UTC, joaander commented on hoomd/md/force.py
> +        particle type and stays constant during the simulation.
```suggestion
        Active torque vector in local reference frame of the particle
        :math:`[\mathrm{force} \cdot \mathrm{length}]`. It is defined per
        particle type and stays constant during the simulation.
```

2021-08-31 11:18 UTC, joaander commented on hoomd/md/methods/methods.py
> -    def _detach(self):
Is this now handled by the base class?

2021-08-31 11:18 UTC, joaander commented on hoomd/md/update.py
> +    The rotational diffusion is applied to the orientation vector/quaternion
```suggestion
    The rotational diffusion is applied to the orientation quaternion
```

2021-08-31 11:18 UTC, joaander commented on hoomd/md/update.py
> +    rotational diffusion is performed tangent plane of the manifold.
```suggestion
    rotational diffusion is performed in the tangent plane of the manifold.
```

2021-08-31 11:18 UTC, joaander commented on hoomd/md/update.py
> +        active_force (hoomd.md.force.Active): The active force associated with
Document that `hoomd.md.force.ActiveOnManifold` is also an accepted type.

2021-08-31 11:18 UTC, joaander commented on hoomd/md/update.py
> +    Args:
Move the Args section to the top of the docstring so that it appears close to the argument list when sphinx renders it.

2021-08-31 20:09 UTC, b-butler commented on hoomd/md/methods/methods.py
> -    def _detach(self):
Yes.

2021-09-02 12:38 UTC, joaander commented
Some of the tests are failing:
```
FAILED install/hoomd/md/pytest/test_active_rotational_diffusion.py::test_pickling[CPU-Active]
FAILED install/hoomd/md/pytest/test_active_rotational_diffusion.py::test_pickling[CPU-ActiveOnManifold]
```

2021-09-02 20:30 UTC, joaander approved these changes
Thanks!

2021-09-02 20:30 UTC, merged