OverdampedViscous method
glotzerlab/hoomd-blue pull request #1121
Opened 2021-08-28 21:45 UTC by danevans09

## Description

This implements a new MD method in python, `OverdampedViscous`, that is an overdamped integrator with a drag force but no random force. This class uses the C++ `Brownian` integrator with `noiseless_t` and `noiseless_r` set to `True`.

## Motivation and context

In the version 2 API, `noiseless_t` and `noiseless_r` were arguments to the Python `Brownian` integrator. These arguments were removed in version 3, so this `OverdampedViscous` class re-enables simulations that are on the Brownian time scale with a drag force but have no Brownian force or torque.

Resolves #1100 

## How has this been tested?

I added the `OverdampedViscous` method to `test_methods.py`

## Change log

```
Added: Overdamped integrator with a drag force but no random force ``hoomd.md.methods.OverdampedViscous``
```

## Checklist:

- [X] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [X] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [X] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2021-08-30 18:07 UTC, joaander requested changes
Thanks @danevans09 ! I have some suggestions for improvement. Also: Add OverdampedViscous to the summary and class list in the appropriate `.rst` files so they appear in the documentation.

One of the suggestions involves making minor modifications to the behavior of Brownian at the C++ level. This will implement a long requested for feature where users on the mailing list have asked for useful velocity data from their active particle integrators. You might add a `Tip:` in the method docs that this method is useful for active matter to provide a search term users might look for in the docs.

2021-08-31 12:05 UTC, joaander requested changes
Thanks!

Please correct the warnings issued by pre-commit. 

Also, I forgot to mention that the RATTLE BD integrator has a separate implementation in `TwoStepRATTLEBD.h` and `TwoStepRATTLEBDGPU.cuh` those also need modifications to handle the velocity setting. I think you only need to modify the first step of the integration method as the `includeRATTLEForce` method handles the `noiseless_t` variable correctly and doesn't set velocities. The part of the code that projects the velocity into the tangent plane should be executed in both branches, the only difference is that when `noiseless_t` is set, the velocity to project is not random but is force over gamma. Ask @SchoeniPhlippsn if you have any questions about these methods.

@pepak13 it would be great to hear your thoughts on these changes.

2021-09-01 19:16 UTC, joaander requested changes
One last change request.

2021-09-01 19:16 UTC, joaander commented on hoomd/md/methods/rattle.py
> +        forces=[lj])
```suggestion
        odv_rattle = hoomd.md.methods.rattle.OverdampedViscous(
            filter=hoomd.filter.All(), manifold_constraint=sphere, seed=1,
            alpha=1.0)
        integrator = hoomd.md.Integrator(
            dt=0.001, methods=[odv_rattle], forces=[lj])
```
Make the line splits more readable.

2021-09-02 04:50 UTC, danevans09 commented
Ok great! Thank you for letting me implement this.

2021-09-02 12:57 UTC, joaander approved these changes
Thanks!

2021-09-02 12:57 UTC, merged