Evaluator pair dlvo bug fix
glotzerlab/hoomd-blue pull request #1143
Opened 2021-09-21 15:14 UTC by NathanDavisBarrett

## Description

There appears to be a missing file in the _md_headers portion of the hoomd/md/CMakeLists.txt file.
I propose that the file "EvaluatorPairDLVO.h" be added so that it can be included externally from hoomd (i.e. in a plugin)

This is because EvaluatorPairDLVO.h is not referenced in hoomd/md/CMakeLists.txt

I just added it in the appropriate place.

## Motivation and context

When trying to include the file hoomd/md/EvaluatorPairDLVO.h from an external plugin, the compiler throws an error since the file is not copied into the python module's "include" folder.

Adding a reference to the file allows for the file to be copied over to the python module at compile time and therefore enables it to be included by an external plugin.

Resolves #1142

## How has this been tested?

1. I added a reference to EvaluatorPairDLVO.h in the _md_headers section of hoomd/md/CMakeLists.txt
2. I compiled and install hoomd with this change.
3. I checked to make sure EvaluatorPairDLVO.h is in python3.9/site-packages/hoomd/include/hoomd/md (which it is, after the change)

## Change log

```
2021-09-21  Nathan Barrett  <ndb.nathan.barrett@gmail.com>

    * hoomd/md/CMakeLists.txt (_md_headers): added "EvaluatorPairDLVO.h"
    
    * sphinx-doc/credits.rst: added "Nathan Barrett, Pritzker School of Molecular Engineering"
```

## Checklist:

- [ x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2021-09-21 15:52 UTC, joaander requested changes
Please revert the irrelevant changes.

In the future, consider using `git add <file>` and `git commit` to commit only specific changes. 

I will squash merge this branch to simplify the history. Alternately, you could make a new branch with only commits 72c1394 and 6638c48 cherry-picked in it, then force push that branch here.

2021-09-21 15:52 UTC, joaander commented on hoomd/md/TwoStepNVE.h
> +/*! Implements velocity-verlet+ NVE integration through the IntegrationMethodTwoStep interface
```suggestion
/*! Implements velocity-verlet NVE integration through the IntegrationMethodTwoStep interface
```

2021-09-21 15:52 UTC, joaander commented on hoomd/md/integrate.py
> +        super()._attach()
```suggestion
```

2021-09-21 19:27 UTC, NathanDavisBarrett commented
Sorry about that, I was created the brach from the wrong point.
It should be good to go now.

2021-09-22 14:23 UTC, joaander approved these changes
Thanks!

2021-09-22 15:39 UTC, merged