Document theory the md component.
glotzerlab/hoomd-blue pull request #1263
Opened 2022-03-01 18:03 UTC by joaander

## Description

This is a full edit pass on the documentation of the `hoomd.md` package, with special attention to ensuring that the actions of operations are formally explained with mathematical notation (https://github.com/glotzerlab/hoomd-blue/issues/1078).

## Motivation and context

Ensure that the documentation is clear, consistent, accurate, and unambiguous.

Resolves #1078
Resolves #1262 
Resolves #1229

## How has this been tested?

I inspected the rendered documentation locally.

## Change log

```
Documentation improvements.
```

## Checklist:

- [X] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [X] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [X] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2022-03-10 18:54 UTC, b-butler requested changes
This took a lot of effort. Great work. I have left comments for typos, fixes, and potential clarifications. For the most part I tried to use suggestions where applicable.

2022-03-10 18:54 UTC, b-butler commented on hoomd/md/pair/pair.py
> +    `Buckingham` computes the `DPD` thermostat combined with the `LJ` pair force
```suggestion
    `DPDDJ` computes the `DPD` thermostat combined with the `LJ` pair force
```

2022-03-10 18:54 UTC, b-butler commented on hoomd/md/pair/pair.py
> +        * ``use_charge`` (`boolean`, **optional**) - evaluate pair force
```suggestion
        * ``use_charge`` (`bool`, **optional**) - evaluate pair force
```

2022-03-11 16:48 UTC, joaander commented on hoomd/md/integrate.py
> +        dt (float): Integrator time step size :math:`[\mathrm{time}]`.
I don't see anything wrong in the local build. Will check the rtd build.

2022-03-11 16:55 UTC, joaander commented on sphinx-doc/module-md-nlist.rst
> +    :show-inheritance:
I prefer not to show empty bases. I used `autoclass` in other files, I just missed this one. Either way we list the classes, they need to be listed explicitly in the rst file - it makes no difference to me whether they are in the `:members:` list or as `autoclass` directives as needed with different options.

2022-03-11 17:56 UTC, joaander commented
The changes to `readthedocs.yml` and `sphinx-doc/environment.yml` fix the readthedocs build failures currently affecting all branches. The switch to `mamba` cuts the time to build the docs down to 90 seconds (from 300+).

2022-03-11 17:57 UTC, joaander commented on hoomd/md/integrate.py
> +        dt (float): Integrator time step size :math:`[\mathrm{time}]`.
The readthedocs build looks the same. What do you see that isn't rendering correctly?

2022-03-14 14:57 UTC, b-butler commented on hoomd/md/integrate.py
> +        dt (float): Integrator time step size :math:`[\mathrm{time}]`.
Hmm, it looked wrong on readthedocs when I first looked at it, but glad it/my eyes are fixed now.

2022-03-14 14:57 UTC, b-butler commented
`mamba` for the win (I use it on all the machines I have access to).

2022-03-14 15:00 UTC, b-butler approved these changes
:+1:

2022-03-14 15:23 UTC, merged