Fix Tag equality check behavior
glotzerlab/hoomd-blue pull request #1288
Opened 2022-03-28 15:26 UTC by chrisjonesBSU

## Description

Creating a set filter from two tag filters would give an attribute error when checking for equivalence when the tag filters were of different sizes. This PR replaces `all()` with `np.array_equal()`

## Motivation and context

See #1285 

## How has this been tested?

I added a unit test that tests the `__eq__` function in `tags.py` directly. If this isn't sufficient I can add a test that creates a Union from two tag filters as well. 

## Change log

```

```

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2022-03-28 16:39 UTC, b-butler requested changes
@chrisjonesBSU this is fine. I have one suggested change to the test, and then this should be good.

2022-03-28 16:39 UTC, b-butler commented on hoomd/pytest/test_filter.py
> +    assert filter_d.__eq__(filter_a) == True
```suggestion
    assert filter_a != filter_b
    assert filter_b != filter_c
    assert filter_d == filter_a
```

2022-03-28 16:39 UTC, b-butler approved these changes
LGTM

2022-04-04 11:18 UTC, joaander commented
@Tobias-Dwyer, please review. This short pull request was posted 7 days ago.

2022-04-04 16:14 UTC, Tobias-Dwyer approved these changes
Looks good :-D

2022-04-05 12:58 UTC, joaander commented
Change log entry:

```
Fixed:

* Prevent ``TypeError: 'bool' object is not iterable`` errors when comparing ``Tag`` filters with different lengths arrays.
```

2022-04-05 12:59 UTC, merged