Make GSDReader set z box members to 0 in 2D boxes.
glotzerlab/hoomd-blue pull request #1313
Opened 2022-05-04 15:09 UTC by b-butler

## Description

Fixes bug with HOOMD 2.x generated GSD files which required non zero Lz
which in v3 is regarded as a 3D box.

## Motivation and context

Resolves #1312

## How has this been tested?

## Change log

```
- Fixed: Reading in 2D boxes generated in HOOMD v2 now correctly results in a 2D box on both the Python and C++ side.
```

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2022-05-04 15:54 UTC, joaander commented
@tcmoore3 does this fix the issue in your tests?

2022-05-04 17:29 UTC, tcmoore3 commented
@joaander Yes. For a system of hard triangles in 2D, the `betaP` value logged by the compute is identical to the value I calculate manually from the SDF data.

2022-05-04 17:30 UTC, tcmoore3 approved these changes
LGTM!

2022-05-04 17:40 UTC, joaander commented
@mariaward10 feel free to review if you like, but Tim's review and test meets the 2nd review needed for this pull request.

2022-05-04 18:58 UTC, tommy-waltmann requested changes
Just one small thing, then this should be ready to go.

2022-05-04 18:58 UTC, tommy-waltmann commented on hoomd/pytest/test_simulation.py
> +        f.close()
This can be written so there is only 1 `if device.communicator.rank == 0` check.

2022-05-04 19:34 UTC, tommy-waltmann requested changes

2022-05-04 19:34 UTC, tommy-waltmann commented on hoomd/pytest/test_simulation.py
> +                f.append(modify_gsd_snap(make_gsd_snapshot(snap)))
```suggestion
    if device.communicator.rank == 0:
        for step in checks:
            f.append(modify_gsd_snap(make_gsd_snapshot(snap)))
```

2022-05-05 20:04 UTC, tommy-waltmann approved these changes

2022-05-05 20:28 UTC, merged