Pickle logging tests
glotzerlab/hoomd-blue pull request #1335
Opened 2022-05-20 17:45 UTC by kodyt

## Description

Addresses #1310 by adding basic `test_logging` and `test_pickling` functions to the unaccounted forces.
## Motivation and context

Resolves #1310 
 
## How has this been tested?

This is the test

## Change log

```
Adds test_logging and test_pickling functions to test_bond.py, test_angle.py, test_dihedral.py, 
test_improper.py, test_special_pair.py, test_external.py, and test_wall_potential.py. 
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2022-05-24 16:08 UTC, syjlee approved these changes
Looks good to me.

2022-05-25 12:29 UTC, joaander requested changes
Thanks! This is clean and complete. Thanks for also configuring your git identity correctly.

I have one suggestion for improvement (see the inline comment below).

2022-05-25 12:29 UTC, joaander commented on hoomd/md/pytest/test_angle.py
> +                                 }
This dictionary is repeated for all the Force logging checks. Store this in `conftest.py` and reuse the variable in all locations to reduce code duplication.

2022-05-25 15:48 UTC, kodyt commented on hoomd/md/pytest/test_angle.py
> +                                 }
That's a good idea, I will fix that.

2022-05-26 14:25 UTC, joaander approved these changes
Thanks!

2022-05-26 14:25 UTC, merged