Fix/incorrect log category
glotzerlab/hoomd-blue pull request #1344
Opened 2022-06-06 20:58 UTC by b-butler

## Description

Fixes a bug in the logging category of `hoomd.md.Integrate.linear_momentum`.
Adds a function `modify_namespace` that allows classes to have custom namespaces (irrespective of the auto namespacing mechanism).

## Motivation and context

In a simulation script the logging failed for this reason, and the new function is to enable `hoomd.md.Integrate` to be more consistent to our namespace approach, and is public to allow users ultimate flexibility in namespaces.

## How has this been tested?
`hoomd.md.Integrate` is tested for its loggables now.
`modify_namespace` is implicitly tested by `hoomd/md/pytest/test_integrate.py`

## Change log

```
- Added: A decorator for modifying the namespace of operation and custom action classes ``hoomd.logging.modify_namespace``
- Fixed: The logging category of ``hoomd.md.Integrate.linear_momentum``
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2022-06-07 14:33 UTC, tommy-waltmann commented on hoomd/md/integrate.py
>      r"""Molecular dynamics time integration.
What was the logging namespace for this previously? I don't understand why `Integrator`'s logging namespace needs to be manually changed.

2022-06-09 14:47 UTC, rayasare approved these changes
Looks good

2022-06-13 14:40 UTC, b-butler commented on hoomd/md/integrate.py
>      r"""Molecular dynamics time integration.
`("md", "integrate", "Integrator")` versus now `("md", "Integrator") which is how we expose it to the user.

2022-06-13 20:52 UTC, tommy-waltmann requested changes
I would like to see a test added which makes sure the new `modify_namespace` function works

2022-06-13 22:45 UTC, b-butler commented
@tommy-waltmann this is tested directly by the new logging test for `hoomd/md/pytest/test_integrator.py` would you want a separate test?

2022-06-14 16:40 UTC, tommy-waltmann commented
No, that's okay. I misunderstood what the `logging_check` function in conftest was doing.

2022-06-14 16:40 UTC, tommy-waltmann approved these changes

2022-06-14 17:03 UTC, merged