Fix/filter updater
glotzerlab/hoomd-blue pull request #1360
Opened 2022-07-11 17:51 UTC by b-butler

## Description

This modifies `SyncedList` to behavior like other HOOMD objects in its type validation/processing.

## Motivation and context
Resolves #1359

## How has this been tested?
Added new tests that checks for correct behavior.

## Change log

```
Fixed: ``hoomd.update.FilterUpdater`` now accepts ``hoomd.filter.CustomFilter`` subclasses.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2022-07-11 18:41 UTC, joaander requested changes
This looks good to me. I have suggestion for improvement.

You also need to fix the broken tests.

2022-07-11 18:41 UTC, joaander commented on hoomd/pytest/test_filter_updater.py
> +    filter_list.pop()
This is fragile to future changes to `filter_list`. You could instead filter `filter_list` to remove custom filters.

2022-07-12 15:23 UTC, b-butler commented on hoomd/pytest/test_filter_updater.py
> +    filter_list.pop()
Good point. Addressing now.

2022-07-13 13:07 UTC, joaander approved these changes
Thanks!

2022-07-13 13:15 UTC, joaander commented
@tcmoore3, do you approve?

2022-07-14 21:45 UTC, tcmoore3 commented
Looks good!

2022-07-14 21:46 UTC, tcmoore3 approved these changes

2022-07-15 11:32 UTC, merged