Feat/movement limited method
glotzerlab/hoomd-blue pull request #1363
Opened 2022-07-15 19:04 UTC by b-butler

## Description

- Creates `hoomd.md.methods.DisplacementCapped` and `hoomd.md.methods.rattle.DisplacementCapped` methods
- Changes `TwoStepNVE` to use a `Variant` as its displacement limitation.

## Motivation and context

Resolves #1261i

## How has this been tested?

The two classes have been added to existing tests.

## Change log

```
Added: ``hoomd.md.methods.DisplacementCapped`` class for relaxing configurations with overlaps.
Added: ``hoomd.md.methods.rattle.DisplacementCapped`` class for relaxing configurations with overlaps.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2022-07-18 15:15 UTC, joaander requested changes
Thanks! I have some suggestions to improve the documentation.

2022-07-18 15:15 UTC, joaander commented on hoomd/md/methods/methods.py
> +    `MotionCapped` integrates integrates translational and rotational degrees of
Replace all `MotionCapped` with `DisplacementCapped`.

2022-07-18 15:15 UTC, joaander commented on hoomd/md/methods/methods.py
> +    r"""Modified constant volume, constant energy dynamics with a cap on motion.
I would describe this as "Newtonian dynamics with a cap on the maximum displacement per time step".

2022-07-18 15:15 UTC, joaander commented on hoomd/md/methods/rattle.py
> +    r"""NVE-like integration with capped displacement.
I would describe this as "Newtonian dynamics with a cap on the maximum displacement per time step".

2022-07-18 15:15 UTC, joaander commented on hoomd/md/methods/rattle.py
> +
Add a warning block stating that displacement capped dynamics are not energy or momentum conserving.

2022-07-18 15:15 UTC, joaander commented on hoomd/md/methods/methods.py
> +
Add a warning block stating that displacement capped dynamics are not energy or momentum conserving.

2022-07-18 16:54 UTC, syjlee approved these changes
This PR looks good to me, and I agree with Josh's comments about doc.

2022-07-21 02:29 UTC, joaander requested changes
Add `DisplacementCapped` to the two methods rst files so it appears in the documentation.

2022-08-08 17:02 UTC, joaander requested changes
Two more quick changes. The examples in the docs would fail with `SyntaxError` or `TypeError`.

2022-08-08 17:02 UTC, joaander commented on hoomd/md/methods/rattle.py
> +            filter=hoomd.filter.All(),maifold=sphere)
```suggestion
        relax_rattle = hoomd.md.methods.rattle.DisplacementCapped(
            filter=hoomd.filter.All(), maximum_displacement=0.01, maifold=sphere)
```

2022-08-08 17:02 UTC, joaander commented on hoomd/md/methods/methods.py
> +            filter=hoomd.filter.All(), 1e-3)
```suggestion
        relaxer = hoomd.md.methods.DisplacementCapped(
            filter=hoomd.filter.All(), maximum_displacement=1e-3)
```

2022-08-10 15:13 UTC, joaander approved these changes

2022-08-10 15:51 UTC, merged