Constant force
glotzerlab/hoomd-blue pull request #1425
Opened 2022-10-26 23:03 UTC by SchoeniPhlippsn

Reimplemented and rewritten the constant force class  

## Description

Users can now add a constant force and constant torque on particles selected by a filter. 

## Motivation and context

It was a feature of HOOMD v2 and is faster than using the custom force approach

## How has this been tested?

Added pytests and ran some simulations with it.

## Change log

```
Reimplementation of a constant force and constant torque class
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2022-10-31 13:14 UTC, joaander requested changes
Thanks for this, it will be very useful. I have a number of requested changes, most only on variable naming conventions. There is one performance bug I noticed.

Do you have a strong use-case that justifies the need for type-specific parameters in addition to the filter? When does this work better than multiple `force.Constant` instances with different filters and only single fixed force and torque values? I ask because the current behavior is somewhat counterintuitive and will take some additional documentation to explain fully. Users will be confused why there are two ways to select which particles get which forces.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +#include "hoomd/RandomNumbers.h"
```suggestion
```
Not used.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +/*! \param rotation_diff rotational diffusion constant for all particles.
```suggestion
/*! \param group Group to apply constant force to.
```

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +    // allocate memory for the per-type constant_force storage and initialize them to (0,0,0)
```suggestion
    // allocate memory for the per-type constant torque storage and initialize them to (0,0,0)
```

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +    GlobalVector<Scalar3> tmp_f_constantVec(m_pdata->getNTypes(), m_exec_conf);
```suggestion
    GlobalVector<Scalar3> tmp_f(m_pdata->getNTypes(), m_exec_conf);
```
This variable name mixes naming conventions. I think `tmp_f` is sufficiently descriptive.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +    GlobalVector<Scalar3> tmp_t_constantVec(m_pdata->getNTypes(), m_exec_conf);
```suggestion
    GlobalVector<Scalar3> tmp_t(m_pdata->getNTypes(), m_exec_conf);
```
Same here.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +        throw std::invalid_argument("gamma_r values must be 3-tuples");
```suggestion
        throw std::invalid_argument("force values must be 3-tuples");
```

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +    Scalar3 f_constantVec;
```suggestion
    Scalar3 force;
```
Naming conventions.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +    Scalar3 f_constantVec = h_f_constantVec.data[typ];
```suggestion
    Scalar3 force = h_f_constantVec.data[typ];
```
Naming conventions.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +        throw std::invalid_argument("gamma_r values must be 3-tuples");
```suggestion
        throw std::invalid_argument("torque values must be 3-tuples");
```

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +    Scalar3 t_constantVec;
```suggestion
    Scalar3 torque;
```

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.cc
> +    Scalar3 t_constantVec = h_t_constantVec.data[typ];
```suggestion
    Scalar3 torque = h_t_constantVec.data[typ];
```

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.h
> +        m_f_constantVec; //! constant force unit vectors and magnitudes for each particle type
```suggestion
        m_constant_force; //! constant force vectors for each particle type
```
Similarly, all handles to this should be `h_constant_force` or `d_constant_force`.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.h
> +        m_t_constantVec; //! constant torque unit vectors and magnitudes for each particle type
```suggestion
        m_constant_torque; //! constant torque for each particle type
```
Similarly, all handles to this should be `h_constant_torque` or `d_constant_torque`.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceCompute.h
> +    bool m_need_rearrange_forces; //!< True if forces need to be rearranged
```suggestion
    bool m_parameters_updated; //!< Set to true when the user changes parameters.
```
The old variable name doesn't reflect the current usage.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceComputeGPU.cc
> +    m_t_constantVec.swap(tmp_t_constantVec);
```suggestion
```
Why is this here? The base class initializes these member variables, so there is no need to reinitialize them.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/ConstantForceComputeGPU.cc
> +    }
This fails to set `m_need_rearrange_forces = false;`, so `setForces` will be called every time step. Better to set `m_need_rearrange_forces = false;` in the base class `computeForces` method.

2022-10-31 13:14 UTC, joaander commented on hoomd/md/force.py
> +        constant.constant_torque['A','B'] = (0,0,0)
```suggestion
        constant.constant_force['A'] = (1,0,0)
        constant.constant_torque['A'] = (0,0,0)
```

2022-10-31 13:14 UTC, joaander commented on hoomd/md/force.py
> +        all = hoomd.filter.All()
```suggestion
```

2022-10-31 13:14 UTC, joaander commented on hoomd/md/force.py
> +    by the filter:
```suggestion
    `Constant` applies a type dependent constant force and torque on all particles selected
    by the filter:
```

2022-10-31 13:14 UTC, joaander commented on hoomd/md/pytest/test_constant_force.py
> +
Check the values of `constant.force` and `constant.torque` as well.

2022-11-04 13:47 UTC, joaander requested changes
Thanks, this is a big improvement!

In addition to the in-line suggested `numpy.assert_array_equal(constant.forces ...`, please add tests with 1) multiple particle types and 2) filters that are not `All` to ensure that the output in `forces` and `torques` is as expected.

2022-11-04 13:47 UTC, joaander commented on hoomd/md/pytest/test_constant_force.py
> +
```suggestion
assert numpy.assert_array_equal(constant.forces, [[0.5, 0.0, 0.0], [0.5, 0.0, 0.0]])
assert numpy.assert_array_equal(constant.torques, [[0.0, 0.0, 1.0], [0.0, 0.0, 1.0]])
```

2022-11-04 13:47 UTC, joaander commented on hoomd/md/pytest/test_constant_force.py
> +
```suggestion
import numpy
```

2022-11-04 13:47 UTC, joaander commented on hoomd/md/force.py
> +    particles selected by the filter:
```suggestion
    particles selected by the filter. `Constant` sets the force and torque to 
    ``(0,0,0)`` for particles not selected by the filter.

```

2022-11-04 13:47 UTC, joaander commented on hoomd/md/ConstantForceComputeGPU.cu
> +    hipMemset(d_force, 0, sizeof(Scalar4) * N);
```suggestion
    hipMemset(d_force, 0, sizeof(Scalar4) * N);
    hipMemset(d_torque, 0, sizeof(Scalar4) * N);
```

2022-11-28 17:22 UTC, joaander approved these changes
Thanks! I pushed some changes to address the testing issues.

2022-11-28 17:22 UTC, joaander commented on hoomd/md/force.py
> +        constant during the simulation.
```suggestion
        :math:`[\mathrm{force}]`.  It is defined per particle type and 
        defaults to (0.0, 0.0, 0.0) for all types.
```
It is not necessarily constant, the user can change it. Also, document the default value.

2022-11-28 17:22 UTC, joaander commented on hoomd/md/force.py
> +        particle type and stays constant during the simulation.
```suggestion
        particle type and defaults to (0.0, 0.0, 0.0) for all types.
```

2022-11-28 17:22 UTC, joaander commented on hoomd/md/pytest/test_constant_force.py
> +        constant.constant_force['A'] = (1.0, 2.0, 3.0)
I pushed this change to trigger the autotuner to run on every step of the test. Previously, the kernel only executed once.

2022-11-28 17:22 UTC, joaander commented on hoomd/md/pytest/test_constant_force.py
> +def test_types(simulation_factory, two_particle_snapshot_factory):
I added this test to ensure that forces and torques are correctly set by type.

2022-11-28 17:22 UTC, joaander commented on hoomd/md/pytest/test_constant_force.py
> +    constant = hoomd.md.force.Constant(filter=hoomd.filter.Type(['A']))
I modified this test to ensure that the filter is applied as documented.

2022-11-28 17:33 UTC, shihkual approved these changes
Looks good to me.

2022-11-28 19:47 UTC, merged