Refactor Rigid Bodies Body Definition
glotzerlab/hoomd-blue pull request #1433
Opened 2022-11-09 20:18 UTC by b-butler

## Description
Remove charge/diameter from rigid body definition. Allows setting charges in createRigidBodies, but not diameters since we are removing that.

## Motivation and context
This is one of the main tasks for 4.0.

Resolves #1350

## How has this been tested?
Existed _modified_ tests are sufficient.

## Change log

```
Changed: `hoomd.md.constrain.Rigid` no longer takes `diameters` or `charges` as body arguments. The `create_bodies` method now takes an optional `charges` argument to set charges.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2022-11-11 15:50 UTC, b-butler commented
@joaander the containers are failing to initialize which results in test failing.

2022-11-15 16:50 UTC, joaander commented
@b-butler the tests are now running.

2022-11-15 20:37 UTC, joaander requested changes
Thanks! This turned out to be a minimal change to fix the API.

Update `test_rigid_filter` to work with this change: https://github.com/glotzerlab/hoomd-blue/actions/runs/3438664815/jobs/5803196403#step:6:4513

2022-11-15 20:37 UTC, joaander commented on hoomd/md/ForceComposite.cc
> +#endif
```suggestion
#include <pybind11/stl.h>
```
Check not needed in `.cc` files.

2022-11-15 20:37 UTC, joaander commented on hoomd/md/ForceComposite.cc
> +            charges_vector.emplace_back(charge.cast<float>());
```suggestion
            charges_vector.emplace_back(charge.cast<Scalar>());
```

2022-11-15 20:37 UTC, joaander commented on hoomd/md/ForceComposite.cc
> +        std::vector<float> charges_vector;
```suggestion
        std::vector<Scalar> charges_vector;
```

2022-11-15 20:37 UTC, joaander commented on hoomd/md/constrain.py
> +            charges (dict[str, float], optional): The charges for each of the
```suggestion
            charges (dict[str, list[float]], optional): The charges for each of the
```

2022-11-22 18:15 UTC, joaander commented
`test_filter_md.py` is still failing.

2022-11-22 18:18 UTC, b-butler commented
Sorry missed that.

2022-11-22 18:37 UTC, joaander commented
We also need to make a `trunk-major` branch on https://github.com/glotzerlab/hoomd-examples, set it to build the `trunk-major` branch of HOOMD for testing, and update the rigid body tutorial to match the new API.

2022-11-22 18:51 UTC, joaander approved these changes
Thanks! This looks good.

One small change is needed so that flake8 will pass.

2022-11-22 18:51 UTC, joaander commented on hoomd/md/constrain.py
> +                charges are zero. The keys should be the central particles.
```suggestion
            charges (dict[str, list[float]], optional): The charges for each of
                the constituent particles, defaults to ``None``. If ``None``,
                all charges are zero. The keys should be the central particles.
```
fix: `hoomd/md/constrain.py:304:81: E501 line too long (83 > 80 characters)`

2022-11-22 22:31 UTC, joaander commented
Reminder to update the tutorial: https://github.com/glotzerlab/hoomd-examples/issues/72

2022-11-22 22:32 UTC, merged