fix: Add deprecation warnings to deprecated features.
glotzerlab/hoomd-blue pull request #1485
Opened 2023-02-07 21:11 UTC by b-butler

## Description

## Motivation and context

Resolves #???

## How has this been tested?

## Change log

```

```

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-02-08 13:34 UTC, joaander requested changes
Thanks! Shouldn't these all be `FutureWarning` as you have said previously?

2023-02-08 13:36 UTC, joaander commented
Also, some tests are failing: https://github.com/glotzerlab/hoomd-blue/actions/runs/4118267747/jobs/7110757262#step:6:5523

2023-02-08 16:01 UTC, b-butler commented
Depends. Do we want to warn users for something they can't fix? My opinion is to error on that side, but I know that other HOOMD developers such as yourself disagree, so I don't want to just force my opinion through.

2023-02-08 16:13 UTC, joaander commented
I have stated that I don't want to provide non-silencable warnings. You mentioned that the user can control the Python warning subsystem to silence `FutureWarning`. If the code to do so is not obvious in the documentation (https://docs.python.org/3/library/warnings.html#module-warnings) then we should provide a how to guide in HOOMD.

I agree that `DeprecationWarning` is useless as few, if any, HOOMD users will run their scripts with the proper environment variables, command line options, or warnings filter code to display those.

2023-02-09 17:15 UTC, b-butler commented on sphinx-doc/migrating.rst
> +===================
```suggestion
===================

```

2023-02-09 20:25 UTC, joaander approved these changes
Thanks! 

I applied minor edits directly to the branch.

2023-02-09 20:58 UTC, merged