Thermalize particle momenta
glotzerlab/hoomd-blue pull request #1527
Opened 2023-03-24 16:16 UTC by melodyyzh

## Description
When the `All` filter is used on `thermalize_particle_momenta`, it assigns non-zero values to the velocities and angular momenta of rigid body constituent particles. These non-zero values are not be overwritten by `hoomd.md.constrain.Rigid`. This PR modified`thermalize_particle_momenta` to assign zero constituent particle velocities and angular momenta. 

## Motivation and context

Resolves #1472 

## How has this been tested?
Added a test function in `test_state.py` 

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-03-24 16:26 UTC, melodyyzh commented
I have a couple of questions here: 
(1) in `ParticleGoup.cc`, when we loop around all the particles in a group, I believe these particles include both center and constituent particles. So I added an if statement by comparing `h_body` and `h_tag` to see if the particle is center or constituent. I am not sure if this logic is correct, since this change breaks the original 2 tests (`test_thermalize_particle_velocity` and `test_thermalize_angular_momentum`). 
(2) in the new test (`test_zero_particle_velocity_angmom`), I am currently using `thermalized_snapshot.particles.velocity.all()` to compare the velocity and angmom to 0. The test failed because velocity and angmom are not zero for **all** the particles. Is there some way I can restrict the comparison of constituent particles? 

Thank!!

2023-03-31 14:16 UTC, tommy-waltmann requested changes
Great work on this @melodyyzh! I have one comment which will fix the failing unit tests with MPI, and two others which are mostly minor and won't affect unit testing results.

2023-03-31 14:16 UTC, tommy-waltmann commented on hoomd/ParticleGroup.cc
> +                                     access_mode::readwrite);
```suggestion
                                     access_mode::read);
```
We're not going to modify the body tag data in this method, so just access it for reading.

2023-03-31 14:16 UTC, tommy-waltmann commented on hoomd/ParticleGroup.cc
> +        // Generate zero velocities and momenta for constituent particles
```suggestion
        // Generate a random velocity, excluding constituent particles
```

2023-03-31 14:16 UTC, tommy-waltmann commented on hoomd/pytest/test_state.py
> +    snapshot.particles.moment_inertia[:] = [[1, 1, 1]] * 4
Remember to check if the process is on rank 0 before updating the snapshot's particle data.

2023-04-03 14:20 UTC, joaander requested changes
Thanks! I have suggestions to improve this.

2023-04-03 14:20 UTC, joaander commented on hoomd/ParticleGroup.cc
> +        if (h_tag.data[j] != h_body.data[j] && h_body.data[j] != static_cast<unsigned int>(-1))
```suggestion
        if (h_tag.data[j] != h_body.data[j] && h_body.data[j] != NO_BODY)
```
Use defined constants in place of hard-coded values.

2023-04-03 14:20 UTC, joaander commented on hoomd/ParticleGroup.cc
> +        if (h_tag.data[j] == h_body.data[j] || h_body.data[j] == static_cast<unsigned int>(-1))
```suggestion
        if (h_tag.data[j] == h_body.data[j] || h_body.data[j] == NO_BODY)
```

2023-04-03 14:20 UTC, joaander commented on hoomd/ParticleGroup.cc
> +        if (h_tag.data[j] == h_body.data[j] || h_body.data[j] == static_cast<unsigned int>(-1))
```suggestion
        if (h_tag.data[j] == h_body.data[j] || h_body.data[j] == NO_BODY)
```

2023-04-03 14:24 UTC, tommy-waltmann approved these changes
Once Josh's comments are addressed, this will be ready to go.

2023-04-03 15:57 UTC, joaander approved these changes
Thanks!

2023-04-03 15:58 UTC, merged