Various fixes for v4 docs
glotzerlab/hoomd-blue pull request #1545
Opened 2023-05-09 17:54 UTC by DomFijan

## Description

Several examples at various places in the docs were incorrect (md example in readme, new thermostat examples etc.). I've also updated some thermostat docstrings with additional examples. 

## Motivation and context

Hopefully makes docs better.

## How has this been tested?

## Change log

```

```

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-05-15 19:48 UTC, b-butler requested changes
Thanks @DomFijan for the fixes. I have made some suggestions.

2023-05-15 19:48 UTC, b-butler commented on hoomd/md/methods/methods.py
>          nph = hoomd.md.methods.ConstantPressure(filter=hoomd.filter.All(),
should be npt
```suggestion
        npt = hoomd.md.methods.ConstantPressure(filter=hoomd.filter.All(),
```

2023-05-15 19:48 UTC, b-butler commented on hoomd/md/methods/methods.py
>          nph = hoomd.md.methods.ConstantPressure(filter=hoomd.filter.All(),
```suggestion
        npt = hoomd.md.methods.ConstantPressure(filter=hoomd.filter.All(),
```

2023-05-15 19:48 UTC, b-butler commented on hoomd/md/methods/methods.py
>          nph = hoomd.md.methods.ConstantPressure(filter=hoomd.filter.All(),
```suggestion
        npt = hoomd.md.methods.ConstantPressure(filter=hoomd.filter.All(),
```

2023-05-15 19:48 UTC, b-butler commented on hoomd/md/methods/thermostats.py
> +        integrator = hoomd.md.Integrator(dt=dt, methods=[nvt], forces=[lj])
There are no forces defined. Perhaps we should remove that part of the example.
```suggestion
        integrator = hoomd.md.Integrator(dt=dt, methods=[nvt])
```

2023-05-15 19:48 UTC, b-butler commented on hoomd/md/methods/thermostats.py
> +        integrator = hoomd.md.Integrator(dt=0.005, methods=[nvt], forces=[lj])
```suggestion
        integrator = hoomd.md.Integrator(dt=0.005, methods=[nvt])
```

2023-05-15 19:48 UTC, b-butler commented on hoomd/md/methods/thermostats.py
> +        integrator = hoomd.md.Integrator(dt=dt, methods=[nvt], forces=[lj])
```suggestion
        integrator = hoomd.md.Integrator(dt=dt, methods=[nvt])
```

2023-05-16 01:45 UTC, DomFijan commented
@b-butler thanks for this. At last dev meeting it was mentioned (not sure by whom, perhaps @joaander ) that preferably examples should be such that they can be copy-pasted, since users tend to copy paste these examples.
In this light, do you think it would be better to complement the example with, like:
```
nl = nlist.Cell()
lj = pair.LJ(nl, default_r_cut=3.0)
```
or would you be in favor of getting rid of `forces = [lj]` as you outlined in the suggestion?

2023-05-16 09:10 UTC, joaander commented
> @b-butler thanks for this. At last dev meeting it was mentioned (not sure by whom, perhaps @joaander ) that preferably examples should be such that they can be copy-pasted, since users tend to copy paste these examples. In this light, do you think it would be better to complement the example with, like:
> 
> ```
> nl = nlist.Cell()
> lj = pair.LJ(nl, default_r_cut=3.0)
> ```
> 
> or would you be in favor of getting rid of `forces = [lj]` as you outlined in the suggestion?

Yes, I mentioned this. There is an argument for both. Without `forces = [lj]`, the user can copy and paste any of these blocks and they will work provided they have `integrator.forces = [force1, force2, ...]` elsewhere in their code.

On the other hand, with the neighbor list and lj boilerplate, the example is 2 lines closer to being a complete copyable example. Users would need to provide `lj.params` for all their particle types. I defer to users to decide which is more better.

2023-05-16 14:40 UTC, b-butler commented
I prefer without LJ as I would rather not assume things of the users' needs. Also, like @joaander said it would still require further specification, and technically running without forces is not an error.

2023-05-16 17:40 UTC, DomFijan commented
Makes sense. Removed.

2023-05-19 19:11 UTC, b-butler approved these changes

2023-05-22 10:27 UTC, merged