Optional `particles/N` and `configuration/box` in GSD files.
glotzerlab/hoomd-blue pull request #1550
Opened 2023-05-10 16:59 UTC by joaander

## Description

Add `'particles/N'` and `'configuration/box'` to the `GSD.dynamic` parameter. Include these with `'property'` so the default behavior is not changed.

## Motivation and context

These chunks take up space in the file. When writing log-only files, `'particles/N'` and/or `'configuration/box'` may not be needed and significantly increase the size of the file.

## How has this been tested?

Added unit tests.

## Change log

```
Added:

* `'particles/N'` and `'configuration/box'` to the `GSD.dynamic` parameter.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-05-10 19:47 UTC, tommy-waltmann requested changes
One small comment, otherwise it looks good.

2023-05-10 19:47 UTC, tommy-waltmann commented on hoomd/md/pytest/test_gsd.py
> +            assert not f.chunk_exists(frame=1, name='particles/position')
Let's add a check that `particles/position` doesn't exist in frame 0 either.

2023-05-11 15:13 UTC, joaander commented on hoomd/md/pytest/test_gsd.py
> +            assert not f.chunk_exists(frame=1, name='particles/position')
Done.

2023-05-11 15:31 UTC, tommy-waltmann approved these changes

2023-05-12 13:27 UTC, merged