Fix/pytest warnings
glotzerlab/hoomd-blue pull request #1557
Opened 2023-05-19 18:17 UTC by b-butler

## Description
Removes pytest warnings about test functions returning values, and this was a good reminder to clean up the test code in `test/operation.py` as well. The PR uses fixtures to modify an operation through its various states for use in testing.

## Motivation and context

Prevents future errors in upcoming pytest versions.

Resolves #???

## How has this been tested?

Tests pass and semantically have not be changed except to test more.

## Change log
Not user facing.
```

```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-05-22 19:03 UTC, joaander commented
After merging #1551, getting these warnings now:
```
pytest/test_simulation.py::test_initialization[CPU]                                                         
  /Users/joaander/venv/lib/python3.11/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function Simulation.__del__ at 0x1064a7ec0>                              
                                                                                                                                                                                                                          0x140f523  Traceback (most recent call last):                                                                                                                                                                                     
    File "/Users/joaander/build/hoomd/hoomd/simulation.py", line 466, in __del__                                                                                                                                         
      self._operations._unschedule()                                                                        
      ^^^^^^^^^^^^^^^^                                                                                      
  AttributeError: 'Simulation' object has no attribute '_operations'                                                                                                                                                     
                                                      
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))    
```
```
md/pytest/test_alchemostat.py::test_after_attaching[CPU-NVT-extra_property_1st_value0-extra_property_2nd_value0]                                                                                                         
  /Users/joaander/venv/lib/python3.11/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function Simulation.__del__ at 0x1064a7ec0>                              
                                                                                                                                                                                                                         
  Traceback (most recent call last):                                                                                                                                                                                     
    File "/Users/joaander/build/hoomd/hoomd/simulation.py", line 466, in __del__                                                                                                                                         
      self._operations._unschedule()                                                                                                                                                                                     
    File "/Users/joaander/build/hoomd/hoomd/operations.py", line 194, in _unschedule                                                                                                                                     
      self._integrator._detach()                                                                                                                                                                                         
    File "/Users/joaander/build/hoomd/hoomd/operation.py", line 259, in _detach                                                                                                                                          
      self._detach_hook()                                                                                                                                                                                                
    File "/Users/joaander/build/hoomd/hoomd/md/integrate.py", line 60, in _detach_hook                                                                                                                                   
      self._methods._unsync()                                                                                                                                                                                            
    File "/Users/joaander/build/hoomd/hoomd/data/syncedlist.py", line 259, in _unsync                                                                                                                                    
      self._unregister_item(item)                                                                                                                                                                                        
    File "/Users/joaander/build/hoomd/hoomd/data/syncedlist.py", line 207, in _unregister_item                                                                                                                           
      value._detach()                                                                                                                                                                                                    
    File "/Users/joaander/build/hoomd/hoomd/operation.py", line 259, in _detach                                                                                                                                          
      self._detach_hook()                                                                                                                                                                                                
    File "/Users/joaander/build/hoomd/hoomd/md/alchemy/methods.py", line 36, in _detach_hook                                                                                                                             
      self._alchemical_dof._unsync()                                                                                                                                                                                     
    File "/Users/joaander/build/hoomd/hoomd/data/syncedlist.py", line 259, in _unsync                                                                                                                                    
      self._unregister_item(item)                                                                           
    File "/Users/joaander/build/hoomd/hoomd/data/syncedlist.py", line 207, in _unregister_item                                                                                                                           
      value._detach()                                                                                                                                                                                                    
    File "/Users/joaander/build/hoomd/hoomd/operation.py", line 259, in _detach                                                                                                                                          
      self._detach_hook()                             
    File "/Users/joaander/build/hoomd/hoomd/md/alchemy/pair.py", line 202, in _detach_hook                                                                                                                               
      self._force._cpp_obj.disableAlchemicalPairParticle(self._cpp_obj)                                                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                 
  AttributeError: 'NoneType' object has no attribute 'disableAlchemicalPairParticle'        
```
```
md/pytest/test_active_rotational_diffusion.py::test_pickling[CPU-ActiveOnManifold]                                                                                                                                       
  /Users/joaander/venv [...]

2023-05-22 21:13 UTC, tommy-waltmann reviewed
The code looks good. Just need to fix the new warnings that are now being generated.

2023-05-31 19:54 UTC, b-butler commented
Before merging I need to fix other warnings that I missed as my hodges dev environment had an older version of pytest.

2023-06-05 14:23 UTC, b-butler commented
pre-commit.ci autofix

2023-06-05 22:45 UTC, tommy-waltmann requested changes
Just one friendly suggestion for re-wording a comment.

2023-06-05 22:45 UTC, tommy-waltmann commented on hoomd/simulation.py
> +        # return early not to raise an exception.
```suggestion
        # _operations may not be set, check before unscheduling
```

2023-06-07 14:09 UTC, joaander commented
Please also merge `trunk-patch` (now 4.0.0) and resolve conflicts.

2023-06-12 20:26 UTC, tommy-waltmann approved these changes
LGTM

2023-06-15 17:02 UTC, merged