Account for grid shift in CPPExternalPotential
glotzerlab/hoomd-blue pull request #1564
Opened 2023-05-25 01:42 UTC by tcmoore3

## Description

Account for grid shift in member functions of C++ class `ExternalFieldJIT`.

## Motivation and context

Fixes a bug.

Resolves #1562 

## How has this been tested?

I updated the `test_gravity` unit test to be more robust. I have also observed the correct behavior in the simulation mentioned in #1562. 

## Change log

```
- Fix bug in hpmc.external.user.CPPExternalPotential
```

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-05-25 14:01 UTC, joaander requested changes
Thanks for the fix. I have suggestions for improvement.

2023-05-25 14:01 UTC, joaander commented on hoomd/hpmc/pytest/test_external_user.py
We discussed improvements to the test offline.

2023-05-25 14:01 UTC, joaander commented on hoomd/hpmc/ExternalFieldJIT.h
> +            vec3<Scalar> old_pos_i = vec3<Scalar>(*(position_old + i));
* `old_pos_i` must be shifted bo the old origin, which the caller must provide.
* `IntegratorHPMC::attemptBoxResize` should scale the origin.

2023-05-26 15:52 UTC, joaander requested changes
Thanks! This looks to be exactly what we need to fix external fields in HPMC with box moves.

I would like to see a test for this. First let's look at the trajectory of a simulation run (not a unit test) and see if we can identify a way to write a unit test. You could use your existing harmonic test, though I think it the results might be more clear if we instead place disks outside of a cylindrical wall. 

Before this fix: when run in MPI, the origin will shift inconsistently with the particles, so at some point particles will either end up stuck inside the cylinder and/or the cylinder may appear to diffuse through the simulation box. After this fix, the trajectory should look normal with particles moving around a fixed cylinder.

2023-05-26 15:52 UTC, joaander commented on hoomd/hpmc/IntegratorHPMC.cc
> +    Scalar3 old_origin = m_pdata->getOrigin();
Excellent. Please make similar changes to `BoxResizeUpdater.cc`.

2023-05-26 15:52 UTC, joaander commented on hoomd/hpmc/UpdaterBoxMC.cc
> +        m_pdata->translateOrigin(-origin_shift);
Excellent. Please make similar changes to `UpdaterQuickCompress.cc`.

2023-05-30 21:54 UTC, tcmoore3 commented
> Thanks! This looks to be exactly what we need to fix external fields in HPMC with box moves.
> 
> I would like to see a test for this. First let's look at the trajectory of a simulation run (not a unit test) and see if we can identify a way to write a unit test. You could use your existing harmonic test, though I think it the results might be more clear if we instead place disks outside of a cylindrical wall.
> 
> Before this fix: when run in MPI, the origin will shift inconsistently with the particles, so at some point particles will either end up stuck inside the cylinder and/or the cylinder may appear to diffuse through the simulation box. After this fix, the trajectory should look normal with particles moving around a fixed cylinder.

@joaander and I worked out a test that highlights the unexpected behavior, which I will summarize here for future reference. The test system is a system of hard spheres initially at a low packing fraction with an HPMC integrator with move size 0 and a `hpmc.update.BoxMC` updater set to `betaP = 10`. As the simulation runs, the box updater causes the system density to increase. Before the fix (specifically, using the v3.10 release), the grid shift is apparent if you track the trajectories of individual particles as the system compresses; the trajectories appear as wavy lines. In contrast, the trajectories are straight lines with this fix. The attached figure illustrates these differences. Note that in this example, only the "dynamics" are affected and the thermodynamics are still correct. However, in cases where a potential energy function depends on spatial coordinates, as discussed in #1562, the thermodynamics of the system are also incorrect.
![image](https://github.com/glotzerlab/hoomd-blue/assets/5814680/a82fb615-3dce-4748-98c5-f6d9bda39121)

This fix may also resolve the behavior described in #568.

2023-05-31 17:41 UTC, joaander approved these changes
Thanks!

2023-05-31 17:42 UTC, merged