Add Missing HPMC Headers
glotzerlab/hoomd-blue pull request #1573
Opened 2023-06-12 15:53 UTC by tommy-waltmann

## Description

This PR adds some headers which are in hoomd's source, but do not get installed with hoomd.

## Motivation and context

Many of HPMC's headers do not get installed with hoomd, preventing users from building hpmc-based plugins.

## How has this been tested?

I have not tested this locally yet, but will soon.

## Change log

```
- All of HPMC's headers are now installed with hoomd.
```

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-06-13 15:48 UTC, tommy-waltmann commented
I have tested locally and I can now build my hpmc plugin.

2023-06-14 13:17 UTC, joaander approved these changes
Thanks for the fix.

If you would like to test this fix in CI, add a HPMC shape example plugin. The CI workflow builds and installs hoomd, then compiles the example plugins separately to ensure that they can find all the needed headers: https://github.com/glotzerlab/hoomd-blue/blob/79431aa329f1cc5ff40707a059cfa9909a902675/.github/workflows/test.yml#L122-L134

2023-06-21 20:12 UTC, joaander reviewed
This looks good so far, here are a few suggestions. We should include a minimal unit test that constructs and attaches the example shape.

2023-06-21 20:12 UTC, joaander commented on hoomd/hpmc/integrate.py
> +            self._cpp_obj = getattr(_ext_module,
```suggestion
            self._cpp_obj = getattr(self._ext_module,
```

2023-06-21 20:12 UTC, joaander commented on hoomd/hpmc/integrate.py
> +            self._cpp_obj = getattr(_ext_module, self._cpp_cls)(sys_def)
```suggestion
            self._cpp_obj = getattr(self._ext_module, self._cpp_cls)(sys_def)
```

2023-06-21 20:12 UTC, joaander commented on example_plugins/shape_plugin/ShapeMySphere.h
> +    }
```suggestion
```
Let's not worry about NEC support in a minimal example plugin.

2023-06-21 20:12 UTC, joaander commented on example_plugins/shape_plugin/ShapeMySphere.h
> +#endif
```suggestion
```
User-defined shapes are unlikely to have a type_shapes specification.

2023-06-21 20:12 UTC, joaander commented on example_plugins/shape_plugin/integrate.py
> +
```suggestion
from . import _shape_plugin
```

2023-07-10 13:59 UTC, joaander requested changes
Almost there!

2023-07-10 13:59 UTC, joaander commented on example_plugins/shape_plugin/CMakeLists.txt
> +    )
I think the test is failing because `__init__.py` is missing entirely and both `integrate.py` and `__init__.py` are not in the `files` list.

2023-07-10 13:59 UTC, joaander commented on example_plugins/shape_plugin/pytest/test_mysphere.py
> +    intgrator = shape_plugin.integrate.MySphere()
Add a test that attaches the `MySphere` integrator.

2023-07-18 19:25 UTC, tommy-waltmann commented
pre-commit.ci autofix

2023-07-26 13:31 UTC, joaander requested changes
Thanks!
The GPU build is failing: https://github.com/glotzerlab/hoomd-blue/actions/runs/5591634178/job/15145507676?pr=1573#step:7:31

To fix, add a `.cu` file that manually expands all these template files for the example template: https://github.com/glotzerlab/hoomd-blue/blob/efbeae37947a739146f8e7fc1da151db34366db5/hoomd/hpmc/CMakeLists.txt#L105-L125

You can merge all these into a single .cu file. For example:
```
#include "ComputeFreeVolumeGPU.cuh"
#include "IntegratorHPMCMonoGPUDepletantsAuxilliaryPhase1.cuh"
// ... more includes from the other files

namespace hoomd
    {
namespace hpmc
    {
namespace gpu
    {
template void
hpmc_depletants_auxilliary_phase1<ShapeMySphere>(const hpmc_args_t& args,
                                                      const hpmc_implicit_args_t& implicit_args,
                                                      const hpmc_auxilliary_args_t& auxilliary_args,
                                                      const ShapeMySphere::param_type* params);

template hipError_t
gpu_hpmc_free_volume<ShapeMySphere>(const hpmc_free_volume_args_t& args,
                                         const typename ShapeMySphere::param_type* d_params);
    // ... more explicit templates from the other files.

    } // namespace gpu

    } // end namespace hpmc
    } // end namespace hoomd

2023-08-03 20:31 UTC, joaander approved these changes
Thanks!

I made the final changes needed for the tests to pass.

2023-08-03 20:31 UTC, merged