Update mpcd initialization for v4
glotzerlab/hoomd-blue pull request #1580
Opened 2023-06-21 18:19 UTC by matthewddo

## Description

Update snapshot and system data to new API

## Motivation and context

It didn't work anymore. :)

Resolves #???

## How has this been tested?

Pytest unit tests are being ported

## Change log

```

```

## Checklist:

- [X] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [X] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-06-26 14:41 UTC, joaander commented
Please maintain equal performance for non-MPCD users and be aware of the `get_snapshot` performance improvements I made in #1538.

Write as little or as detailed information in the change log and migration guide as you prefer.

2023-07-14 16:23 UTC, mphoward commented
> Please maintain equal performance for non-MPCD users and be aware of the `get_snapshot` performance improvements I made in #1538.

Sounds good! We will check in #1538 and apply to MPCD since it was copied originally.

For non-MPCD users, I think these changes will fully preserve performance since there is very little overhead to the empty MPCD data structures, similarly to the topology data structures. We can be even more aggressive than we currently are, though, and not allocate *any* MPCD data if there are no particles present in the snapshot.

For MPCD users, I anticipate `get_snapshot` is going to get very slow if the user only wants access to the MD data, since it will pull all the MPCD data if present. This would not be desirable if someone wanted to do something with only the MD particles (common use case) in a snapshot. A related issue is possible in `set_snapshot`, where partial initialization may be desirable (e.g., only initialize from part of a snapshot). I propose adding boolean flags to the principle groups of data initialized with the following defaults:
```
state.get_snapshot(particles=True, topology=True, mpcd=None)
state.set_snapshot(particles=True, topology=True, mpcd=None)
```
(`None` converting to `True` in MPCD builds and `False` in non-MPCD builds). This would preserve the current defaults. I can open a separate issue after this PR is ready so we can discuss this separately.

FYI: this is still a WIP, but we are getting closer.

2023-07-26 18:03 UTC, mphoward commented on hoomd/mpcd/Communicator.cc
> +    m_cl->computeDimensions();
Need to add a check that `m_cl` is not null

2023-07-26 18:03 UTC, mphoward commented on hoomd/mpcd/__init__.py
> +        #None: _md.IntegratorAnisotropicMode.Automatic,
This was a quick hack to get this to run. Will make an empty dict before merging, then this will be rewritten later anyway.

2023-07-26 18:03 UTC, mphoward commented on hoomd/snapshot.py
> +        """
Maybe use `hoomd.version` to check for MPCD support and error out first, that will simplify what comes next.

2023-07-26 18:03 UTC, mphoward commented on hoomd/snapshot.py
> +            Set ``N`` to change the size of the arrays.
We need to note here that this is only when built with MPCD.

2023-07-26 18:11 UTC, mphoward commented on hoomd/snapshot.py
> +        """
```
if not hoomd.version.mpcd_built:
    raise ...
```

2023-07-26 18:16 UTC, mphoward commented on hoomd/mpcd/Communicator.cc
> +    m_cl->computeDimensions();
Put this at top of function.
```
if (!m_cl)
    {
    throw std::runtime_error("Cell list must be set");
    }
```
See base `CollisionMethod`

2023-07-28 03:47 UTC, cslominski commented
The flags BUILD_MPCD and BUILD_VALIDATION (which appears to only be used in mpcd) are undocumented either by HOOMD or by the command `cmake -LAH`. I am turning off BUILD_MPCD and am not specifying BUILD_VALIDATION in my builds. Are these the correct settings, and could this information please be added to the documentation moving forward? Thanks.

2023-07-28 15:39 UTC, joaander commented
@cslominski `BUILD_VALIDATION` will be removed and `BUILD_MPCD` will be documented by this pull request or a future pull request in this series.

2023-07-31 21:20 UTC, mphoward commented
pre-commit.ci autofix

2023-08-02 17:11 UTC, mphoward reviewed
Just a few small things to cleanup and then this is ready for review.

I accidentally merged `trunk-major` in when I meant `trunk-minor`. I think this did not add anything, and I still just need to merge in `trunk-minor` and fix small merge conflicts.

2023-08-02 17:11 UTC, mphoward commented on hoomd/CMakeLists.txt
> +if (BUILD_MPCD)
We need the same check as below on HIP here, or we will get compile errors.

2023-08-02 17:11 UTC, mphoward commented on hoomd/mpcd/data.py
I think this entire file probably should be removed at this point.

2023-08-02 17:12 UTC, mphoward commented
> @cslominski `BUILD_VALIDATION` will be removed and `BUILD_MPCD` will be documented by this pull request or a future pull request in this series.

`BUILD_VALIDATION` is now removed. I will make a note to redocument `BUILD_MPCD`, since it will now affect compilation.

2023-08-03 15:08 UTC, joaander commented
> I accidentally merged `trunk-major` in when I meant `trunk-minor`. I think this did not add anything, and I still just need to merge in `trunk-minor` and fix small merge conflicts.

Correct. `trunk-major` is currently behind `trunk-minor` (I synchronize these on releases).

2023-08-11 16:56 UTC, tommy-waltmann requested changes
Great work so far on the C++ code, it looks like all the necessary changes have been made there!

Now, the python side of the code needs to be updated. Python classes need to be reorganized to use the new data structures for exposing properties in python. The names of the classes should also be capitalized and base classes should not have underscores before the class names.

After that, some basic tests can be written which make sure the python classes are functioning properly. I think some of the current C++ tests can be replaced by equivalent python tests, but that is an optional detail for later.

2023-08-11 16:56 UTC, tommy-waltmann commented on hoomd/mpcd/pytest/test_snapshot.py
> +def test_make(snap):
```suggestion
def test_get_set_mpcd_data(snap):
```
I would like to see this test have a name more specific to what its doing.

2023-08-11 16:56 UTC, tommy-waltmann commented on hoomd/mpcd/pytest/test_snapshot.py
> +def test_resize(snap):
```suggestion
def test_resize(snap):
    """Test that snapshot can be resized without losing data."""
```
Personally, I like to put these little descriptions of what the test is doing in a one line docstring.

2023-08-11 16:56 UTC, tommy-waltmann commented on hoomd/mpcd/pytest/test_snapshot.py
> +def test_create_from_snap(snap, simulation_factory):
This test assumes it gets launched with either 1 or 2 ranks, we should have a line which skips the test if this is not true.

2023-08-11 16:56 UTC, tommy-waltmann commented on hoomd/mpcd/pytest/test_snapshot.py
> +def test_bad_typeid(snap, simulation_factory):
```suggestion
def test_bad_typeid(snap, simulation_factory):
    """Test for typeid out of range."""
```

2023-08-11 16:56 UTC, tommy-waltmann commented on hoomd/mpcd/pytest/test_snapshot.py
> +def test_bad_positions(snap, simulation_factory):
```suggestion
def test_bad_positions(snap, simulation_factory):
    """Check for position outside the box."""
```

2023-08-11 16:56 UTC, tommy-waltmann commented on hoomd/mpcd/pytest/test_snapshot.py
> +def test_take_restore(snap, simulation_factory):
There is a lot of repeat code between this test and the previous one, and they do very similar things. Can the code be reorganized so there is no duplicated code between them?

2023-08-14 16:44 UTC, mphoward commented
All suggestions have been applied! For your other comments:

> Now, the python side of the code needs to be updated. Python classes need to be reorganized to use the new data structures for exposing properties in python. The names of the classes should also be capitalized and base classes should not have underscores before the class names.

Yes, this will be done in many additional pull requests. This PR only implements the particle data / initialization interfaces, as the rest of the code cannot be tested without this change. The next PR should be the `Integrator`.

> After that, some basic tests can be written which make sure the python classes are functioning properly.

Yes, there is an entire suite of Python tests that was removed during the v3 port and needs to be copied over & updated:

https://github.com/glotzerlab/hoomd-blue/tree/v2.9.7/hoomd/mpcd/test-py

For example, `test_snapshot.py` is a reimplementation of `data_snapshot_test.py`.

> I think some of the current C++ tests can be replaced by equivalent python tests, but that is an optional detail for later.

I do not plan to replace the C++ tests because (1) they are already written and (2) test some things that are critical for the algorithm to work correctly but are not (and should not be) exposed at the Python level.

2023-08-14 21:17 UTC, tommy-waltmann reviewed
Sounds good! FWIW, I think the rest of the python stuff can be done in a single PR and doesn't need to be split up into a long series.

2023-08-15 18:08 UTC, mphoward commented
> Sounds good! FWIW, I think the rest of the python stuff can be done in a single PR and doesn't need to be split up into a long series.

@joaander and I had discussed this a while ago, and we both think doing this in a few PRs will be easier to review. The MPCD python code & tests are probably a few thousand lines. Some of the MPCD objects also don't derive from any of the existing HOOMD classes, so new code will be needed there. I am of course planning to logically group changes into PRs when possible!

2023-08-15 18:17 UTC, tommy-waltmann commented
> > Sounds good! FWIW, I think the rest of the python stuff can be done in a single PR and doesn't need to be split up into a long series.
> 
> @joaander and I had discussed this a while ago, and we both think doing this in a few PRs will be easier to review. The MPCD python code & tests are probably a few thousand lines. Some of the MPCD objects also don't derive from any of the existing HOOMD classes, so new code will be needed there. I am of course planning to logically group changes into PRs when possible!

Ok, whatever works.

2023-08-15 18:18 UTC, tommy-waltmann approved these changes

2023-08-18 18:16 UTC, mphoward commented
There is still one open review request from @klywang, but I think this PR is otherwise ready to merge!

Does somebody need to manually trigger the validation tests? Maybe I can do that, but I'm not sure how.

2023-08-22 17:21 UTC, joaander requested changes
Thanks! I have one change request.

2023-08-22 17:21 UTC, joaander commented on hoomd/CMakeLists.txt
> +    target_compile_definitions(_hoomd PUBLIC ENABLE_MPCD)
```suggestion
    target_compile_definitions(_hoomd PUBLIC BUILD_MPCD)
```
Name this definition consistent with the CMake variable that controls it. Also change all instances where this is used (global search and replace may be useful here).

2023-08-24 17:55 UTC, mphoward commented on hoomd/CMakeLists.txt
> +    target_compile_definitions(_hoomd PUBLIC ENABLE_MPCD)
Done!

2023-08-29 13:05 UTC, joaander approved these changes
Thanks!

2023-08-29 13:06 UTC, merged