Fix plugin bond
glotzerlab/hoomd-blue pull request #1594
Opened 2023-07-25 13:49 UTC by astatt

## Description

A simple bug fix that allows bond potentials to be developed in external plugins in the same way pair potentials are. 

## Motivation and context

Without this fix, an external plugin with a new bond potential will compile but fail to find the bond when run, i.e. the link will still be to `hoomd.md.bond` instead of `external_plugin_name.bond`. The simple fix is to add the same "_ext_module = _md" logic as is present in the pair potential class, see [here](https://github.com/glotzerlab/hoomd-blue/blob/efbeae37947a739146f8e7fc1da151db34366db5/hoomd/md/pair/pair.py#L65). 

Resolves #1591

## How has this been tested?

Tested via small "example_plugin" with a test bond implementation. No major changes to the code, so all other tests and functionalities are unaffected.  No changes to documentation aside from adding contributor name. 

## Change log

```
Fix: Bond potentials can now be implemented via external plugins 
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-07-27 13:14 UTC, tcmoore3 approved these changes
This looks good, thanks for the fix. Echoing [Josh's comment on the issue](https://github.com/glotzerlab/hoomd-blue/issues/1591#issuecomment-1651801758), doing the same for angle, dihedrals, impropers, and special pairs would be good for completeness.

2023-07-27 13:14 UTC, tcmoore3 commented on sphinx-doc/credits.rst
> +* Antonia Statt, Universit of Illinois
```suggestion
* Antonia Statt, University of Illinois
```

2023-07-27 15:45 UTC, b-butler requested changes
Thank for the fix. Just one change, and I think this is good to go.

2023-07-27 15:45 UTC, b-butler commented on hoomd/md/bond.py
> +
Unnecessary. Just leave in base class.
```suggestion
```

2023-07-27 18:17 UTC, astatt commented
As @joaander suggested, the same fix should be done for angles, dihedrals, impropers, and special pairs. Would you prefer that I do this in this fix/pull request, your should we do the other fixes seperately? Even if it's less clean, this is such a small fix, it might be easiest to simply leave this pull request open and do all of the fixes at the same time. @b-butler and @joaander, any preference?

2023-07-27 20:05 UTC, joaander commented
You are welcome to apply the other fixes in this pull request. They are closely related and therefore fine to combine together.

2023-07-31 13:02 UTC, joaander commented
pre-commit.ci autofix

2023-08-03 16:04 UTC, b-butler approved these changes
Thanks @astatt for the PR.

2023-08-03 16:04 UTC, b-butler commented on hoomd/md/bond.py
>          self._cpp_obj = cpp_cls(self._simulation.state._cpp_sys_def, self.width)
This seems to be an unnecessary function (not relevant to this PR though).

2023-08-03 20:33 UTC, merged