Add param_array to CPPExternalPotential
glotzerlab/hoomd-blue pull request #1608
Opened 2023-08-17 01:28 UTC by tcmoore3

## Description

Adds variable parameters to `hpmc.external.user.CPPExternalPotential`, directly analogous to the `param_array`s in the `hpmc.pair.user` classes.

## Motivation and context

Can change parameters in the external potential function.

## How has this been tested?

The existing tests pass, and I have been using it in exploratory simulations for research. I haven't yet, but I will add a more direct unit test of changing the values in `param_array`.

## Change log

```
- Add variable parameters to `hpmc.external.user.CPPExternalPotential`, see ..link to docs..
```

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-08-17 01:30 UTC, tcmoore3 commented
pre-commit.ci autofix

2023-08-22 19:17 UTC, joaander requested changes
Thanks! Changes are needed to not break the existing API and expand testing.

2023-08-22 19:17 UTC, joaander commented on hoomd/hpmc/external/user.py
> +    def __init__(self, code, param_array):
```suggestion
    def __init__(self, code, param_array=[]):
```
Maintain the existing API for backwards compatibility.

2023-08-22 19:17 UTC, joaander commented on hoomd/hpmc/pytest/test_external_user.py
> +valid_constructor_args = [dict(code='return -1;', param_array=[1])]
Also test with no `param_arary` to ensure that the existing API functions.

2023-08-22 19:17 UTC, joaander commented on hoomd/hpmc/pytest/test_external_user.py
> +                                                        param_array=[0])
This code doesn't use `param_array`. It should remain unchanged and should continue to function.

2023-08-22 19:17 UTC, joaander commented on hoomd/hpmc/external/user.py
> +                code=gravity_code, param_array=[])
```suggestion
                code=gravity_code)
```
The user should not need to explicitly set `param_array=[]`. Doing so will break all existing scripts that use `CPPExternalPotential).

Also, update this example to run successfully in Sybil.

2023-08-22 19:17 UTC, joaander commented on hoomd/hpmc/external/user.py
> +            be changed.
Add a Sybil example.

2023-08-22 19:17 UTC, joaander commented on hoomd/hpmc/external/user.py
>              After running zero or more steps, this property cannot be modified.
Add a Sybil example.

2023-08-22 19:17 UTC, joaander commented on hoomd/hpmc/external/user.py
>      @log(requires_run=True)
Add a Sybil example.

2023-09-07 19:34 UTC, Tobias-Dwyer approved these changes
Looks good to me, thanks for adding this functionality.

2023-09-08 11:23 UTC, joaander approved these changes
Thanks!

2023-09-08 11:23 UTC, joaander commented on hoomd/hpmc/pytest/test_external_user.py
> +                                                        param_array=[1])
```suggestion
    ext = hoomd.hpmc.external.user.CPPExternalPotential(code='return 0;')
```
Not needed.

2023-09-08 11:23 UTC, joaander commented on hoomd/hpmc/pytest/test_external_user.py
> +                                                        param_array=[0])
```suggestion
    ext = hoomd.hpmc.external.user.CPPExternalPotential(code='return 0;')
```
Not needed.

2023-09-08 11:59 UTC, merged