Improve performance of accessing per-particle energy, forces, torques, and virials properties
glotzerlab/hoomd-blue pull request #1654
Opened 2023-11-16 03:16 UTC by tcmoore3

## Description

Use the GatherTagOrder class to properly gather the per-particle properties from all ranks instead of the slow, previous implementation. This change should drastically improve the performance of (benchmarks to come):
* ForceCompute::getEnergiesPython()
* ForceCompute::getForcesPython()
* ForceCompute::getTorquesPython()
* ForceCompute::getVirialsPython()

## Motivation and context

Resolves #1539.

## How has this been tested?

## Change log

```
Improve performance of accessing per-particle properties of `Force` objects.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-11-16 15:03 UTC, joaander requested changes
Thanks! I have some suggestions to improve this.

2023-11-16 15:03 UTC, joaander commented on hoomd/ForceCompute.h
> +            }
```suggestion
```
This code is not used.

2023-11-16 15:03 UTC, joaander commented on hoomd/md/pytest/test_custom_force.py
> +                force_arrays.force[:] = -5
Need a non-trivial force vector.

2023-11-16 15:03 UTC, joaander commented on hoomd/md/pytest/test_custom_force.py
> +                force_arrays.torque[:] = np.ones(
We should test values of forces, torques, and virials where all the components are different values. This verifies e.g. that the proper ordering of the virial components is maintained through all the steps of the sorting operation.

Something like:
```
force = numpy.stack(
    (local_snapshot.particles.tag * 3, local_snapshot.particles.tag * 5, local_snapshot.particles.tag * -7), axis=-1)
```

2023-11-16 15:03 UTC, joaander commented on hoomd/ForceCompute.h
> +    template<class Real> struct vec6
```suggestion
    namespace detail {
    template<class Real> struct vec6
```
And a closing brace at the end of the class. This makes it clear that the class is a detail of the implementation and not part of the public API.

2023-11-16 16:33 UTC, b-butler requested changes
@tcmoore3 Thanks for the changes, I have a few suggestions, but otherwise looks good.

2023-11-16 16:33 UTC, b-butler commented on hoomd/ForceCompute.cc
> +        global_energy = local_energy;
```suggestion
        global_energy = std::move(local_energy);
```
I think this will perform a copy? Should we do an explicit `std::move`?

2023-11-16 16:33 UTC, b-butler commented on hoomd/ForceCompute.cc
> +    std::vector<uint32_t> local_tag(m_pdata->getN());
Might be worth a helper function to get sorted local tags. We use the same code in each of the functions.

2023-11-16 16:33 UTC, b-butler commented on hoomd/ForceCompute.cc
> +        global_force = local_force;
```suggestion
        global_force = std::move(local_force);
```
See previous comment about `std::move`.

2023-11-16 16:33 UTC, b-butler commented on hoomd/ForceCompute.cc
> +        global_torque = local_torque;
```suggestion
        global_torque = std::move(local_torque);
```

2023-11-16 16:33 UTC, b-butler commented on hoomd/ForceCompute.cc
> +        global_virial = local_virial;
```suggestion
        global_virial = std::move(local_virial);
```

2023-11-27 16:42 UTC, joaander approved these changes
Thanks!

2023-11-29 15:29 UTC, b-butler approved these changes
Thanks @tcmoore3!

2023-11-29 15:31 UTC, merged