Add vector-valued variants
glotzerlab/hoomd-blue pull request #1685
Opened 2023-12-19 17:54 UTC by tcmoore3

## Description

This PR implements a `VectorVariant` that returns array values as a function of time step, in contrast to the `Variant` classes that return scalar values as a function of the time step.
`VectorVariant` is templated on the length of the array to take advantage of C++'s strong typing.
This PR also implements a `VectorVariantBox` and a handful of subclasses of `VectorVariantBox` that return length-6 arrays for use with functions that take box arguments.

The new `VectorVariant*` C++ classes are implemented in `VectorVariant.[h,cc]`.
In Python, I created a new `variant` package.
The existing (scalar-valued) `Variant`s are defined in the package's `__init__.py` file, and the box vector variant python classes are in `hoomd/variant/box.py`.

## Motivation and context

This functionality is a first step towards fixing several issues, #1640 and #1641. It will also allow us to replace the arguments `box1`, `box2`, and `variant` with a single `hoomd.variant.box.*` argument to make the use of `update.BoxResize` more intuitive.

## How has this been tested?

Existing unit tests pass, and my ad-hoc tests of the new box vector variant classes are passing.
I still need to add proper unit tests for the vector variants.

## Change log

```
- Add `variant.box` classes that describe boxes that change with time step.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2023-12-21 14:03 UTC, joaander requested changes
Thanks! Here are some suggestions to improve this. 

As you already noted, we also need to add unit tests.

2023-12-21 14:03 UTC, joaander commented on hoomd/VectorVariant.h
> +    std::array<Scalar, 6> box_to_array(std::shared_ptr<BoxDim> box)
```suggestion
    static std::array<Scalar, 6> box_to_array(std::shared_ptr<BoxDim> box)
```

2023-12-21 14:03 UTC, joaander commented on hoomd/VectorVariant.h
> +        return m_value;
With the `box_to_array` helper above, we should remove `m_value` entirely and replace it with `return box_to_array(m_box)`.

2023-12-21 14:03 UTC, joaander commented on hoomd/VectorVariant.h
> +                           uint64_t t_start,
To provide backwards compatibility with `update.BoxResize`, this should take `std::shared_ptr<Variant>` as an argument instead of `t_start`, `t_stop`.

2023-12-21 14:03 UTC, joaander commented on hoomd/VectorVariant.h
> +        if (timestep < m_t_start)
To avoid code duplication, use an internal VariantRamp to compute the scale factor. There should be no need for 3 code paths in operator() as the interpolation will naturally range from 0 to 1.

2023-12-21 14:03 UTC, joaander commented on hoomd/__init__.py
> +from hoomd.variant import box
```suggestion
```
Keep the package hierarchy. The names should be `hoomd.variant.box.SomeBoxVariant`, not `hoomd.box.SomeBoxVariant`.

2023-12-21 14:03 UTC, joaander commented on hoomd/update/box_resize.py
> +            hoomd.Box: The box used at the given timestep.
Why all these changes? Sphinx knows we are in the hoomd module, so the `Box` link resolves correctly: https://hoomd-blue.readthedocs.io/en/v4.4.1/module-hoomd-update.html#hoomd.update.BoxResize.get_box

2023-12-21 14:03 UTC, joaander commented on hoomd/variant/__init__.py
>  import typing
```suggestion
import typing
from . import box
```

2023-12-21 14:03 UTC, joaander commented on sphinx-doc/module-hoomd-variant.rst
> +    :nosignatures:
```suggestion
```
No need for an empty auto summary.

2024-01-05 16:35 UTC, melodyyzh commented on hoomd/variant/box.py
> +        box1 = box_preprocessing(box1)
Should this be `box1 = box_preprocessing(initial_box)` and `box2 = box_preprocessing(final_box)`? 
This might be the cause for the error in pre-commit.

2024-01-11 20:58 UTC, tcmoore3 commented on hoomd/variant/box.py
> +        box1 = box_preprocessing(box1)
Nice catch!

2024-01-11 22:34 UTC, tcmoore3 commented on hoomd/update/box_resize.py
> +            hoomd.Box: The box used at the given timestep.
I get warnings when I keep it as `Box`:
```
hoomd-blue/hoomd/update/box_resize.py:docstring of hoomd.update.box_resize.BoxResize.get_box:1: WARNING: more than one target found for cross-reference 'Box': hoomd.variant.box.Box, hoomd.Box, hoomd.box.Box
```
and the documentation generated for `hoomd.update.BoxResize.get_box()` links to `hoomd.variant.box.Box` in this case. Is there a way to ensure sphinx finds the right `Box`?

2024-01-23 16:59 UTC, joaander requested changes
Thanks! I have some more suggestions to improve this.

Also, I plan to merge this after the 4.5.0 release with the expectation that we can add code using box variants (BoxResize, QuickCompress) in the same release that we introduce the variants.

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +
```suggestion
```
Remove duplicate comment.

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +    /** Construct a VectorVariantBoxInterpolate to interpolate between two boxes linearly in time.
```suggestion
    /** Construct a VectorVariantBoxInterpolate to interpolate between two boxes linearly.
```

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +    VariantRamp m_variant; //!< Variant that interpolates between boxes
```suggestion
    VariantRamp m_variant;
```
No need to document the member variable twice.

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +
Class level overview documentation for this and the other classes would be useful.

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +        : m_initial_box(box1), m_final_volume(final_volume), m_variant(0, 1, t_start, t_ramp)
```suggestion
    VectorVariantBoxInverseVolumeRamp(std::shared_ptr<BoxDim> initial_box,
                                      Scalar final_volume,
                                      uint64_t t_start,
                                      uint64_t t_ramp)
        : m_initial_box(initial_box), m_final_volume(final_volume), m_variant(0, 1, t_start, t_ramp)
```

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +    Scalar m_current_volume;
```suggestion
```
Unused.

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +    bool m_is2D;
```suggestion
    bool m_is_2d;
```
Naming conventions.

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +        m_is2D = m_initial_box->getL().z == 0;
```suggestion
        m_is_2d = m_initial_box->getL().z == 0;
```

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +        if (m_is2D)
```suggestion
        if (m_is_2d)
```

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +    } // end namespace detail
```suggestion
```
Unused.

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.cc
> +void export_VectorVariantBox(pybind11::module& m)
```suggestion
void export_VectorVariantBoxClasses(pybind11::module& m)
```
This exports more than `VectorVariantBox`.

2024-01-23 16:59 UTC, joaander commented on hoomd/module.cc
> +    export_VectorVariantBox(m);
```suggestion
    export_VectorVariantBoxClasses(m);
```

2024-01-23 16:59 UTC, joaander commented on hoomd/variant/box.py
> +
```suggestion
```

2024-01-23 16:59 UTC, joaander commented on hoomd/variant/box.py
> +    """Interpolate between two boxes linearly in time.
```suggestion
    """Interpolate between two boxes linearly.
```

2024-01-23 16:59 UTC, joaander commented on hoomd/VectorVariant.h
> +        @param box2 The final box
The python code calls these `initial_box` and `final_box`. Please rename all instances of `box1` to `initial_box` and all instances of `box2` to `final_box` for consistency.

2024-01-23 16:59 UTC, joaander commented on hoomd/variant/box.py
> +    :math:`t \\geq t_{\\mathrm{start}} + t_{\\mathrm{ramp}}`.
This is incorrect, there is no t_start nor t_ramp. Replace this with a copy of the docs from `BoxResize` that explicitly document the interpolation.

2024-01-23 16:59 UTC, joaander commented on hoomd/variant/box.py
> +    """Produce box arrays whose inverse volume changes linearly with time.
```suggestion
    """Produce box arrays whose inverse volume changes linearly.
```

2024-01-23 16:59 UTC, joaander commented on hoomd/variant/box.py
> +    linearly with time. The shape of the box remains constant, that is, the
```suggestion
    linearly. The shape of the box remains constant, that is, the
```

2024-01-23 16:59 UTC, joaander commented on hoomd/variant/box.py
> +    linearly with time. The shape of the box remains constant, that is, the
The ramp is not linear in time. It is constant up to `t_start`, linear between `t_start` and `t_start + t_ramp` and constant after `t_ramp`. Need to explain this concisely in this documentation, possibly with a reference to the scalar `Ramp`.

For example, add a math equation that shows how the volume as a function of time relates to the initial box, final volume, and the ramp function.

2024-01-23 22:35 UTC, b-butler commented on hoomd/variant/__init__.py
> +from hoomd.variant.scalar import Power
```suggestion
from hoomd.variant.scalar import (Variant, Constant, Ramp, Cycle, Power)
```

2024-01-23 22:35 UTC, b-butler commented on hoomd/variant/__init__.py
> +A `Variant` object represents a scalar function of the time step. Some
```suggestion
A `Variant` object represents a function of the time step. Some
```

2024-01-23 23:03 UTC, b-butler reviewed
We should either rename `variant_like` to `scalar_varient_like` or make very clear it is for scalar variants.

The code looks good generally. Just left a few comments and probably won't be able to get back to this.

2024-01-23 23:03 UTC, b-butler commented on hoomd/VectorVariant.h
> +    };
Shouldn't this be a pure virtual function? Is there any reason to have a default implementation that just returns zeros?

2024-01-23 23:03 UTC, b-butler commented on hoomd/VectorVariant.cc
> +    return (*t)(step);
I personally prefer `t->operator()(step)`, but feel free to leave alone.

2024-01-23 23:03 UTC, b-butler commented on hoomd/variant/box.py
> +        """hoomd.Box: the initial box."""
```suggestion
        """hoomd.Box: The initial box."""
```
Docstrings should start with capital letters. Fix elsewhere too.

2024-01-23 23:03 UTC, b-butler commented on hoomd/variant/box.py
> +class Constant(_hoomd.VectorVariantBoxConstant, BoxVariant):
The "don't duplicate code" part of me wants to say we should create a decorator which adds the `box` attributes programmatically with documentation to avoid the boilerplate. Don't do that, I just wanted to document it.

2024-01-23 23:03 UTC, b-butler commented on hoomd/pytest/test_box_variant.py
> +_test_scalar_variant2 = hoomd.variant.Ramp(0, 1, 10, 30)
Make these fixtures without the underscore.

2024-01-23 23:03 UTC, b-butler commented on hoomd/pytest/test_box_variant.py
> +        npt.assert_allclose(box_t(custom_variant, _t), box_to_array(test_box))
```suggestion
    for t, f in ((0, 0), (42, 0), (100, 0), (101, 0.01), (150, 0.5),
                   (175, 0.75), (199, 0.99), (200, 1.0), (250, 1.0), (123456789,
                                                                      1.0)):
        test_box.volume = (1 - f) * _test_box1.volume + f * final_volume
        npt.assert_allclose(box_t(custom_variant, t), box_to_array(test_box))
```

2024-01-23 23:03 UTC, b-butler commented on hoomd/pytest/test_box_variant.py
> +    npt.assert_allclose(box1.tilts, variant(625)[3:])
```suggestion
    for step in (0, 5, 252 125, 625):
        npt.assert_allclose(box1.tilts, variant(step)[3:])
```
There are a lot of opportunities to shorten the code with for loops.

2024-01-24 14:04 UTC, joaander commented on hoomd/VectorVariant.h
> +    };
Exposing pure virtual functions via pybind11 adds a lot of complexity for a minimal benefit in coding style.

2024-02-28 18:01 UTC, joaander approved these changes
Thanks!

I implemented a few minor suggestions directly on the branch. This is good to merge now.

2024-02-28 18:01 UTC, merged