Langevin docs update
glotzerlab/hoomd-blue pull request #1771
Opened 2024-04-25 04:30 UTC by crisbutu

## Description

Made two updates to the documentation related to rotational motion with Langevin dynamics:
1. redefined L as angular velocity instead of angular momentum
2. changed the units of gamma_r from time^-1 to mass * length^2 * time^(-1)

## Motivation and context

Resolves #1768 

## How has this been tested?

Manually made sure the latex changes parsed correctly by pasting them into an online latex editor.

## Change log

```

```

## Checklist:

- [X] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [X] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [X] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2024-04-25 14:16 UTC, tommy-waltmann requested changes
Thanks for the PR, we always like it when external folks contribute fixes!

One more thing for discussion: if $\vec L$ is actually the angular velocity, should we change the variable in the docstring to be $\vec \omega$ so its consistent with standard variable naming conventions?

2024-04-25 14:16 UTC, tommy-waltmann commented on hoomd/md/methods/methods.py
> +            :math:`[\mathrm{mass} \cdot \mathrm{length}^{2} \cdot \mathrm{time}^{-1}]`.
This change is good, make sure to also change the units in the parameter description at the top of the docstring for `default_gamma_r`.

2024-04-25 14:16 UTC, tommy-waltmann commented on hoomd/md/methods/methods.py
> +    the torque, :math:`\vec{L}` is the particle's angular velocity and :math:`I`
```suggestion
    torque, :math:`\vec{L}` is the particle's angular velocity and :math:`I`
```
Not related to units or variables, but I think there is an extra "the" in that sentence.

2024-04-26 03:40 UTC, crisbutu commented
@tommy-waltmann I addressed the comments and this is ready for another look!

2024-04-26 14:09 UTC, tommy-waltmann commented
pre-commit.ci autofix

2024-04-26 14:15 UTC, tommy-waltmann commented
This looks good, we now just need to satisfy the code and documentation style enforced by `pre-commit`. A list of lines that need fixing is included here: https://results.pre-commit.ci/run/github/147663007/1714140577.QTa6j2IcTPmDJO5n3xovrg .

2024-04-26 15:09 UTC, AlainKadar approved these changes

2024-04-26 15:33 UTC, joaander commented
You can get fixes for:
```
hoomd/simulation.py:560:45: E226 missing whitespace around arithmetic operator
sphinx-doc/conf.py:63:21: E201 whitespace after '{'
sphinx-doc/conf.py:63:26: E202 whitespace before '}'
```
by merging the upstream `trunk-patch` into your branch.

2024-04-27 18:34 UTC, crisbutu commented
@tommy-waltmann `pre-commit` now passes

2024-04-29 15:10 UTC, tommy-waltmann approved these changes
Thanks for the fix!

2024-04-29 15:12 UTC, SchoeniPhlippsn approved these changes

2024-05-01 15:19 UTC, merged