Mesh volume conservation
glotzerlab/hoomd-blue pull request #1794
Opened 2024-06-01 18:39 UTC by SchoeniPhlippsn

## Description

This adds a global volume constraint potential which can be applied to the mesh data structure.

## Motivation and context

This volume constraint allows applying a global target volume per mesh type to closed membranes represented by a particle mesh.

## How has this been tested?

I added pytests and used this potential in my current studies.

## Change log

```
Addition of a volume constraint mesh potential
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2024-06-03 16:15 UTC, tommy-waltmann commented on sphinx-doc/module-md-mesh-conservation.rst
> +------------
```suggestion
md.mesh.conservation
-------------------------
```
I think this is why the documentation is failing to build properly.

2024-10-09 03:56 UTC, SchoeniPhlippsn commented
pre-commit.ci autofix

2024-10-09 04:11 UTC, SchoeniPhlippsn commented
pre-commit.ci autofix

2024-10-09 18:00 UTC, SchoeniPhlippsn commented
@joaander @Charlottez112 
Ready for review!

2024-10-16 12:39 UTC, joaander requested changes
Thanks! I have a some suggestions for improvement. You will also need to merge `trunk-minor` with this branch.

2024-10-16 12:39 UTC, joaander commented on hoomd/md/VolumeConservationMeshForceCompute.cc
> +    m_volume = new Scalar[n_types];
`m_volume` is duplicated as `m_volume_GPU` in the subclass. Use `GPUArray<Scalar> m_volume` in the base class and then there is no need to duplicate code.

2024-10-16 12:39 UTC, joaander commented on hoomd/md/mesh/conservation.py
> +        mesh (:py:mod:`hoomd.mesh.Mesh`): Mesh data structure constraint.
Document `ignore_type`

2024-10-16 16:54 UTC, SchoeniPhlippsn commented
pre-commit.ci autofix

2024-10-16 17:00 UTC, SchoeniPhlippsn commented
pre-commit.ci autofix

2024-10-21 12:32 UTC, joaander approved these changes
Thanks!

2024-10-21 12:33 UTC, merged