Mesh area conservation
glotzerlab/hoomd-blue pull request #1795
Opened 2024-06-01 18:51 UTC by SchoeniPhlippsn

## Description

This adds two area constraint potentials which can be applied to the mesh data structure.

## Motivation and context

These area constraints allow applying a global target area per mesh type or a local target area per mesh triangle to membranes represented by a particle mesh.

## How has this been tested?

I added pytests and used this potential in my current studies.

## Change log

```
Addition of area constraint mesh potentials
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2024-10-09 02:18 UTC, SchoeniPhlippsn commented
pre-commit.ci autofix

2024-10-09 02:25 UTC, SchoeniPhlippsn commented
pre-commit.ci autofix

2024-10-09 04:06 UTC, SchoeniPhlippsn commented
pre-commit.ci autofix

2024-10-09 17:59 UTC, SchoeniPhlippsn commented
@joaander @tcmoore3 
Ready for review!

2024-10-16 17:50 UTC, SchoeniPhlippsn commented
pre-commit.ci autofix

2024-10-21 12:39 UTC, joaander requested changes
Thanks! Now that volume conservation is merged, you need to merge `trunk-minor` into this branch and resolve conflicts.

The code looks great. I found a few duplicate or unused lines of code that can be removed.

2024-10-21 12:39 UTC, joaander commented on hoomd/md/TriangleAreaConservationMeshForceCompute.h
> +// Part of HOOMD-blue, released under the BSD 3-Clause License.
```suggestion
```
Duplicate line.

2024-10-21 12:39 UTC, joaander commented on hoomd/md/TriangleAreaConservationMeshForceComputeGPU.cu
> +
```suggestion
```
unused.

2024-10-21 12:39 UTC, joaander commented on hoomd/md/TriangleAreaConservationMeshForceComputeGPU.cu
> +#include <assert.h>
```suggestion
```
unused.

2024-10-23 15:19 UTC, SchoeniPhlippsn commented
pre-commit.ci autofix

2024-10-23 19:35 UTC, joaander approved these changes
Thanks!

2024-10-23 19:48 UTC, merged