Enhancement/md pair gaussian value check
glotzerlab/hoomd-blue pull request #1810
Opened 2024-06-11 18:55 UTC by josephburkhart

## Description

I have modified the `TypeParameterDict` for `md.pair.Gaussian`, `md.pair.ExpandedGaussian`, and `md.pair.LJGaussian` so that `sigma` must be a positive real number. Correspondingly, I have updated docstrings and pytests to reflect the new requirement.

## Motivation and context

This change ensures that users cannot accidentally or mistakenly set `sigma` equal to 0 for any of the Gaussian-type pair potentials, since doing so would cause divide-by-zero errors during simulation execution.

Resolves #1806

## How has this been tested?

I have added new invalid parameter dictionaries to the constructor function `_invalid_params()` in `hoomd/md/pytest/test_potential.py`.

I have built the documentation using Sphinx and confirmed that the changes I made to the docstrings display properly.

## Change log

```
Added a positive-number check to parameters for Gaussian-type pair potentials.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2024-06-12 14:19 UTC, josephburkhart commented
@joaander do you have any suggestions on how I can get the pre-commit.ci check to pass? As far as I can tell, I have ensured that my additions a) have no trailing whitespace and b) satisfy the yapf settings in `setup.cfg`. Am I missing something?

2024-06-12 17:42 UTC, josephburkhart commented
pre-commit.ci autofix

2024-06-14 17:23 UTC, tommy-waltmann requested changes
Thanks for this, just a small fix in where the positive value is documented.

2024-06-14 17:23 UTC, tommy-waltmann commented on hoomd/md/pair/pair.py
>            :math:`\sigma` :math:`[\mathrm{length}]`
```suggestion
        * ``sigma`` (`float`, **required**) - particle size
          :math:`\sigma > 0` :math:`[\mathrm{length}]`
```

2024-06-14 17:23 UTC, tommy-waltmann commented on hoomd/md/pair/pair.py
>            Gaussian width :math:`\sigma` :math:`[\mathrm{length}]`
```suggestion
        * ``sigma`` (`float`, **required**) -
          Gaussian width :math:`\sigma > 0` :math:`[\mathrm{length}]`
```

2024-06-24 10:16 UTC, joaander approved these changes
Thanks!

2024-06-24 10:16 UTC, joaander commented on hoomd/md/pair/pair.py
>            :math:`[\mathrm{length}]`
```suggestion
        * ``sigma`` (`float`, **required**) - particle size :math:`\sigma > 0`
          :math:`[\mathrm{length}]`
```
For consistency.

2024-06-24 13:22 UTC, tommy-waltmann approved these changes
Looks good, thanks for working on this!

2024-06-24 13:59 UTC, merged