Add k_BT to HPMC integrator
glotzerlab/hoomd-blue pull request #1869
Opened 2024-08-15 15:44 UTC by surajkannur

## Description

Previously, $k_BT$ was assumed to be 1. In this PR, $k_BT$ is implemented as a variant in the HPMC integrator.

## Motivation and context

Assuming $k_BT = 1$ meant that the well depth of the potential had to be rescaled to simulate different temperatures in the case of patchy particles. It also made interpreting the $\beta P$ output of the SDF compute difficult. With this change 
the temperature can be user defined.

## How has this been tested?

Reproduce final plot of patchy particle tutorial with $k_BT = 1$
TODO other tests

TODO documentation

## Change log

```
Add $k_BT$ to HPMC integrator
```

## Checklist:

- [ ] IntegratorHPMCMono.h
- [ ] $\mu VT$
- [ ] Cluster moves
- [ ] box moves
- [ ] SDF pressure compute
- [ ] shape moves
- [ ] boxMC
- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2024-09-13 16:15 UTC, surajkannur commented
pre-commit.ci autofix

2024-09-24 16:02 UTC, joaander requested changes
Thanks! I have made several suggestions to improve code style. I also found a bug in `BoxMC` (not your fault, the variable is named incorrectly).

As an added TODO item, we need to modify `hpmc/compute.py`.
- [x] Add `SDF.P` which returns `SDF.betaP * {the current kT}`.

I also considered renaming `betaP` to `P`, but I now think we should keep `betaP` for backwards compatibility. `betaP` is also more natural for purely hard particle systems.

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/ComputeSDF.h
> +    Scalar kT = m_mc->getTimestepkT(timestep); // use const?
```suggestion
    const Scalar kT = (*m_mc->getKT())(timestep);
```
I would prefer that we call `operator()` on `Variant` directly.

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/IntegratorHPMC.cc
> +        .def_property("kT", &IntegratorHPMC::getkT, &IntegratorHPMC::setkT)
```suggestion
        .def_property("kT", &IntegratorHPMC::getKT, &IntegratorHPMC::setKT)
```
We should need only the property.

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/IntegratorHPMC.h
> +        }
```suggestion
    std::shared_ptr<const Variant> getKT()
        {
        return m_kT;
        }
```
The capital K is necessary other wise the first word of the method name appears to be `getk` and the second word as `T`.

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/IntegratorHPMC.h
> +
```suggestion
```
Not necessary.

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/IntegratorHPMC.h
> +    void setkT(std::shared_ptr<Variant> kT)
```suggestion
    void setKT(std::shared_ptr<Variant> kT)
```

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/IntegratorHPMCMono.h
> +            Scalar kT = IntegratorHPMC::getTimestepkT(timestep);
```suggestion
            const Scalar kT = (*m_mc->getKT())(timestep);
```
Also, move this line to the top of the function. `kT` does not vary during the loop, so there is no need to evaluate it every loop iteration.

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/ShapeMoves.h
> +        Scalar kT = m_mc->getTimestepkT(timestep);
```suggestion
        const Scalar kT = (*m_mc->getKT())(timestep);
```

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/ShapeMoves.h
> +               + inertia_term - 3 * N * slow::log(1 / kT);
Why `log(1/kT)` in the last term?

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/UpdaterBoxMC.cc
> +    Scalar kT = m_mc->getTimestepkT(timestep);
```suggestion
    const Scalar kT = (*m_mc->getKT())(timestep);
```

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/UpdaterClusters.h
> +        Scalar kT = m_mc->getTimestepkT(timestep);
```suggestion
        const Scalar kT = (*m_mc->getKT())(timestep);
```

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/UpdaterMuVT.h
> +                    Scalar kT = m_mc->getTimestepkT(timestep);
```suggestion
                    const Scalar kT = (*m_mc->getKT())(timestep);
```
Move this line to the top of the function. `kT` does not need to be reevaluated in the inner loops.

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/UpdaterMuVT.h
> +                Scalar kT = m_mc->getTimestepkT(timestep);
```suggestion
```
Not needed when `kT` is evaluated at the top of the function.

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/UpdaterMuVT.h
> +                Scalar kT = m_mc->getTimestepkT(timestep);
```suggestion
```
Not needed when `kT` is evaluated at the top of the function.

2024-09-24 16:02 UTC, joaander commented on hoomd/hpmc/UpdaterBoxMC.cc
> +    if (allowed && p < exp(-(delta_beta_H + delta_U_pair + delta_U_external) / kT))
This is incorrect and should appear as a failure in validation tests when `kT != 1.0`. The variable named `delta_beta_H` is not what it is named. See lines 501 and 584 - it includes the `log(V_new/V)` term as well. This term should not divided by `kT` (see Frenkel and Smit or https://cassandra-mc.readthedocs.io/en/latest/theory/theory.html#volume-scaling)

To fix, modify `box_resize_trial` to accept an additional parameter: `log_V_term`. Then modify the code around lines 501 and 584 to compute this term and pass it into `box_resize_trial` separately.

2024-10-04 13:35 UTC, joaander commented on hoomd/hpmc/UpdaterBoxMC.cc
> -    if (allowed && p < exp(-(delta_beta_H + delta_U_pair + delta_U_external) / kT) + log_V_term)
Are you sure this change is correct? The cassandra docs show $P\\Delta V$ (which HOOMD calls `delta_beta_H`) multiplied by $\beta$. You can check in Frenkel and Smit to verify.

If you found errors in testing, double check the sign on the `log_V_term`.

2024-11-05 22:07 UTC, joaander approved these changes
Thanks!

2024-11-05 22:27 UTC, merged