Add documentation to hoomd.trigger
glotzerlab/hoomd-blue pull request #790
Opened 2020-10-01 14:51 UTC by syjlee

## Description

There should be documentation for Trigger classes for public facing properties, and methods. 
In addition, class docstrings need to be created

## Motivation and context
Resolves: #718 

## How has this been tested?
Should be checked with locally installed sphinx package, and double check with generated html

## Change log

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2020-10-01 14:52 UTC, syjlee commented
This branch is not ready to be reviews. Will request review once it's ready.

2020-10-07 21:28 UTC, syjlee commented
1. I'm getting the error: `WARNING: py:class reference target not found: hoomd.Trigger`
What is the right reference target for a trigger or a list of triggers as arguments?

2. What would be an appropriate example for `hoomd.trigger.Not`?

Also, could you leave comments what to fix, add or remove?
@joaander @b-butler

2020-10-07 22:18 UTC, joaander commented
> 1. I'm getting the error: `WARNING: py:class reference target not found: hoomd.Trigger`
>    What is the right reference target for a trigger or a list of triggers as arguments?
`hoomd.trigger.Trigger`

> 2. What would be an appropriate example for `hoomd.trigger.Not`?
Perhaps not(on(0))? I can't think of any common use cases for not. Some complex logic can sometimes best be represented by not(and(...)) or not(or(...)).

2020-10-07 22:31 UTC, joaander requested changes
Thanks! This is a great start. I left some comments on the first few triggers. You can apply the same pattern to the remaining ones.

I'll check tomorrow on how to document `compute` and `__call__`. I'll also add some documentation on user defined triggers.

- [x] Document `compute` and `__call__`
- [ ] Provide an example user defined trigger.

2020-10-07 22:31 UTC, joaander commented on hoomd/trigger.py
> +""" :py:class:`hoomd.trigger` enables users to design time points when and while
```suggestion
"""Triggers enable users to design time points when and while
```

2020-10-07 22:31 UTC, joaander commented on hoomd/trigger.py
> +class Trigger(_hoomd.Trigger):  # noqa: D101
We should document this class.
Something like:
```
"""Base class trigger.

Provides methods common to all triggers.

Attention:
    Users should instantiate the subclasses, using `Trigger` directly
    will result in an error.
"""
```

We also need to document the `compute` and `__call__` methods. I need to do some checking and see if I can figure out how to do that with the way we set these classes up in sphinx.

2020-10-07 22:31 UTC, joaander commented on hoomd/trigger.py
> +    R""" Set periodicity of trigger.
```suggestion
    """Trigger periodically.
```

2020-10-07 22:31 UTC, joaander commented on hoomd/trigger.py
> +    :py:class:`hoomd.Operations` operates. The composite of triggers takes
```suggestion
   `hoomd.Operations` operates. The composite of triggers takes 
```
You don't need to preface links. Sphinx can find the right target without the identifier and this is easier to read.

2020-10-07 22:31 UTC, joaander commented on hoomd/trigger.py
> +    `True` every `period` steps ((timestep - phase)/period = 0)
```suggestion
    `True` every `period` steps ``((t - phase) % period = 0``)
```

2020-10-07 22:31 UTC, joaander commented on hoomd/trigger.py
> +    R""" Set the timepoint to finish triger.
```suggestion
    """Trigger every step before a given step.
```

2020-10-07 22:31 UTC, joaander commented on hoomd/trigger.py
> +
```suggestion
```
You shouldn't add these blank lines at the end of the docstrings.

2020-10-09 16:13 UTC, joaander commented
@syjlee I saw you are out today so I revised the docs myself so we can get this finished and included in the first beta release. I took out the GSD, CSV, and other classes from the examples, I think it is cleaner with just the trigger specifications.

2020-10-09 16:14 UTC, joaander approved these changes
Thanks!

2020-10-09 17:49 UTC, syjlee commented
> @syjlee I saw you are out today so I revised the docs myself so we can get this finished and included in the first beta release. I took out the GSD, CSV, and other classes from the examples, I think it is cleaner with just the trigger specifications.

Thanks Josh!

2020-10-13 10:16 UTC, merged