Docs/less hierarchy reqs
glotzerlab/hoomd-blue pull request #890
Opened 2020-12-15 04:28 UTC by cbkerr

## Description

I tried to make the section on install requirements a bit easier to skim by getting rid of the all-encompassing top level heading.
## Motivation and context

## How has this been tested?

## Change log

```

```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2020-12-15 11:12 UTC, joaander requested changes
Thanks, this cleans things up nicely.

Can you fix the list formatting so that sphinx doesn't render the headings with blue banners? Those are definition lists and we want just a normal bulleted list.

Restructured text is *very* particular about list formatting: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#bullet-lists

I'll note a few of the needed changes below.

2020-12-15 11:12 UTC, joaander commented on INSTALLING.rst
> +    - C++11 capable compiler (tested with ``gcc`` 4.8, 5.5, 6.4, 7,
These '-''s need to be in the first column. There also needs to be a blank line between `General requirements` and the start of the list. 
```suggestion

- C++11 capable compiler (tested with ``gcc`` 4.8, 5.5, 6.4, 7,
```

2020-12-15 11:12 UTC, joaander commented on INSTALLING.rst
>      - MPI (tested with OpenMPI, MVAPICH)
Same here:
```suggestion

- MPI (tested with OpenMPI, MVAPICH)
```

2020-12-15 11:12 UTC, joaander commented on INSTALLING.rst
>          - HIP [with ``hipcc`` and ``hcc`` as backend]
In nested lists, there needs to be a blank line before the start *and* the `-` needs to line up with the first character of the parent list text (the backtick above).

2020-12-15 11:12 UTC, joaander commented on INSTALLING.rst
>           A `temporary bugfix branch of HIP <https://github.com/glotzerlab/HIP/tree/hipfuncgetattributes_revertvectortypes>`_
The block starting with `A temporary bugfix branch` no longer applies and should be removed. The ROCm requirement should be increased to >= 3.5.0. (#750).

2020-12-15 18:25 UTC, cbkerr commented
I think I've smoothed out most of the formatting issues.

2020-12-16 00:27 UTC, joaander approved these changes
Thanks!

2020-12-16 00:27 UTC, merged