Convert dump.DCD to v3 API
glotzerlab/hoomd-blue pull request #909
Opened 2021-01-17 21:13 UTC by danevans09

## Description

I created a _dcd.py_ folder in the _hoomd/write_ directory that contains the converted `DCD` class.

## Motivation and context

This pull request converts dump.DCD into the v3 API.

Resolves #881
## How has this been tested?

I tested that the `hoomd.write.DCD` object can be attached to a simulation, and if garnett is installed, I tested that the output in the DCD file is correct.

## Change log

```

```

## Checklist:

- [X] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [X] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [X] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2021-01-18 20:14 UTC, joaander requested changes
Thanks! I have a few changes to request. Most of them are suggestions that you can commit directly in the GitHub PR. One request requires adding some code to `DCDDumpWriter.cc`

2021-01-18 20:14 UTC, joaander commented on hoomd/pytest/test_dcd.py
> +    d.mkdir()
```suggestion
    d = tmp_path
```
`tmp_path` should already be a clean subdirectory - no need to create another subdirectory inside it.

Same for the other tests that follow pattern.

2021-01-18 20:14 UTC, joaander commented on hoomd/pytest/test_dcd.py
> +        sim.run(1)
```suggestion
    sim.run(10)
```
Scheduling is automatic at the first call to `run`.

2021-01-18 20:14 UTC, joaander commented on hoomd/write/dcd.py
> +    R""" Writes simulation snapshots in the DCD format
```suggestion
    """Writes simulation snapshots in the DCD format.
```
PEP8 docstring formatting conventions.

2021-01-18 20:14 UTC, joaander commented on hoomd/write/dcd.py
> +    Every *period* time steps a new simulation snapshot is written to the
```suggestion
    On each timestep where `DCD` triggers, it writes the simulation snapshot the
```

2021-01-18 20:14 UTC, joaander commented on hoomd/write/dcd.py
> +
```suggestion
```
HOOMD v3 does not have `enable` / `disable`.

2021-01-18 20:14 UTC, joaander commented on hoomd/write/dcd.py
> +                          write_settings=[bool],
The way this is implemented, `unwrap_full`, `unwrap_rigid`, and `angle_z` are not accessible as separate parameters. You shouldn't need `write_settings`. Add the appropriate properties to the pybind11 export code for DCD to access these individually.

You'll also need a property for `overwrite` but make it a read only property.

2021-01-18 20:14 UTC, joaander commented on hoomd/write/dcd.py
> +        trigger (hoomd.trigger.Trigger): Select the timesteps to write.
```suggestion
        trigger (hoomd.trigger.Periodic): Select the timesteps to write.
```
Document explicitly that only periodic triggers are allowed.

2021-01-18 20:14 UTC, joaander commented on hoomd/write/dcd.py
> +        raise RuntimeError('The period of a DCD writer cannot be changed')
```suggestion
```
Not needed in v3.

2021-01-18 20:14 UTC, joaander commented on hoomd/write/dcd.py
> +        self._cpp_obj.setAngleZ(write_settings[2])
```suggestion
```
Once these are available as properties in the pybind11 export, `super.attach()` will set them.

2021-01-18 20:14 UTC, joaander commented on hoomd/pytest/test_dcd.py
> +
```suggestion
```
Not needed in v3.

2021-01-18 20:14 UTC, joaander commented on hoomd/pytest/test_dcd.py
> +    garnett = pytest.importorskip("garnett")
Nice! I didn't know this API existed. This is very clean.

I will rebuild the CI images with garnett so this test can run.

2021-01-19 15:50 UTC, joaander approved these changes
Thanks! This looks great.

I made one small change to add DCD to the documentation. @b-butler do you want to review before merging?

2021-01-19 16:08 UTC, joaander requested changes
I spoke too soon. MPI tests are failing. Here is how to fix them:

2021-01-19 16:08 UTC, joaander commented on hoomd/pytest/test_dcd.py
> +        if snap.exists:
Move this `if snap.exists` up to include all code that accesses snap.particles.position.

2021-01-19 16:08 UTC, joaander commented on hoomd/pytest/test_dcd.py
> +    with open(filename, 'rb') as dcdfile:
Wrap the whole open and assert in a `if sim.device.communicator.rank == 0:` check. With the change above, `positions` will only exist on rank 0.

2021-01-19 20:38 UTC, b-butler requested changes
I have a few comments that need to be addressed otherwise, the PR looks good.

2021-01-19 20:38 UTC, b-butler commented on hoomd/write/dcd.py
> +        hoomd.write.DCD("trajectory.dcd", hoomd.trigger.Periodic(1000))
This needs to be set to a variable.

2021-01-19 20:38 UTC, b-butler commented on hoomd/write/dcd.py
> +        When you use dump.dcd to append to an existing dcd file:
```suggestion
        When you use `hoomd.writer.DCD` to append to an existing dcd file:
```
This needs to be changed in a few places.

2021-01-19 20:38 UTC, b-butler commented on hoomd/write/dcd.py
> +                          _defaults=dict(filter=filter)))
Don't use `_defaults` here as this will not check for errors, set the filter after the fact.

2021-01-19 20:38 UTC, b-butler commented on hoomd/pytest/test_dcd.py
> +    snap = sim.state.snapshot
Why do we have this line?

2021-01-19 20:38 UTC, b-butler commented on hoomd/pytest/test_dcd.py
> +        positions.append([list(position1), list(position2)])
`position1` and `position2` won't exist on all ranks here.

2021-01-19 20:38 UTC, b-butler commented on hoomd/pytest/test_dcd.py
> +        positions.append([list(position1), list(position2)])
This needs to be in the conditional.

2021-01-20 12:45 UTC, joaander approved these changes
I couldn't figure out why the MPI tests were failing. Something about the particle positions set in the snapshot caused the simulation run step to deadlock. This isn't an issue that we need to solve right now. I removed the multiple time steps from the test so it should pass now.

Thanks for working on this! @b-butler were all your requests addressed?

2021-01-20 12:47 UTC, joaander commented
/azp run validate

2021-01-20 14:27 UTC, b-butler approved these changes
LGTM, I went ahead an applied yapf to the new files and made the docstring match our 80 character line standard.

@joaander should we make an issue about the deadlock? I don't know if we can expect this to happen elsewhere.

2021-01-20 14:51 UTC, joaander commented
/azp run validate

2021-01-20 14:52 UTC, joaander commented
@b-butler You can file an issue if you want. I suspect it has something to do with running a simulation without an integrator because all of our other MPI tests pass without issues.

2021-01-20 18:24 UTC, merged